<?php

/*
 * This file is part of the PhpNitro package.
 *
 * (c) Ronaldo AWADEME <awademeronaldoo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Engine\Countries;

/**
 * Up to 15 largest cities per country by population — derived from GeoNames' 
 * cities15000 dump (CC BY 4.0, see packages/countries/DATA_LICENSE), filtered
 * and trimmed for embedded/offline size. NOT exhaustive: a full world city
 * gazetteer (GeoNames alone has 4M+ entries) is out of scope for a bundled
 * mobile package — this covers the cities anyone would actually expect to
 * see for city-picker/autocomplete use cases, not a complete gazetteer.
 */
final class CityData
{
    /**
     * @return array<string, array<int, string>> Keyed by ISO 3166-1 alpha-2 code.
     */
    public static function byCountry(): array
    {
        return [
            'AD' => ['Andorra la Vella', 'les Escaldes'],
            'AE' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain City', 'Ajman', 'Dayrah', 'Ras Al Khaimah', 'Musaffah', 'Jebel Ali', 'Business Bay', 'Dubai Investments Park', 'International City', 'Dubai Marina', 'Fujairah', 'Al Majaz'],
            'AF' => ['Kabul', 'Herāt', 'Mazār-e Sharīf', 'Kandahār', 'Jalālābād', 'Kunduz', 'Ghazni', 'Balkh', 'Baghlān', 'Gardez', 'Khōst', 'Maymana', 'Khanabad', 'Bāzār-e Yakāwlang', 'Bāzārak'],
            'AG' => ['Saint John’s'],
            'AI' => ['The Valley'],
            'AL' => ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Lushnjë', 'Berat', 'Fier-Çifçi', 'Korçë', 'Fier', 'Krujë', 'Pogradec', 'Kukës', 'Kuçovë', 'Kavajë'],
            'AM' => ['Yerevan', 'Malatia-Sebastia', 'Shengavit', 'Nor Nork', 'Kentron', 'Erebuni', 'Ajapnyak', 'Arabkir', 'Gyumri', 'Vanadzor', 'Kanaker-Zeytun', 'Avan', 'Davtashen', 'Abovyan', 'Hrazdan'],
            'AO' => ['Luanda', 'Mulenvos', 'Viana', 'Kikolo', 'Maianga', 'Camama', 'Golfe', 'Calumbo', 'Hoji ya Henda', 'Lubango', 'Huambo', 'Benguela', 'Cabinda', 'Talatona', 'Nova Vida'],
            'AR' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mar del Plata', 'San Miguel de Tucumán', 'Salta', 'Santa Fe', 'Avellaneda', 'Corrientes', 'Posadas', 'Bahía Blanca', 'Resistencia', 'Merlo', 'Quilmes', 'San Salvador de Jujuy'],
            'AS' => ['Pago Pago'],
            'AT' => ['Vienna', 'Graz', 'Linz', 'Favoriten', 'Donaustadt', 'Floridsdorf', 'Salzburg', 'Innsbruck', 'Ottakring', 'Simmering', 'Klagenfurt am Wörthersee', 'Landstraße', 'Penzing', 'Meidling', 'Brigittenau'],
            'AU' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Sunshine Coast', 'Canberra', 'Central Coast', 'Logan City', 'Geelong', 'Wollongong', 'Hobart', 'Townsville'],
            'AW' => ['Oranjestad', 'Noord', 'Tanki Leendert', 'Santa Cruz'],
            'AX' => ['Mariehamn'],
            'AZ' => ['Baku', 'Sumgayit', 'Ganja', 'Khirdalan', 'Yevlakh', 'Mingachevir', 'Naxçıvan', 'Lankaran', 'Qaraçuxur', 'Lerik', 'Şirvan', 'Sheki', 'Xaçmaz', 'Bakıxanov', 'Göyçay'],
            'BA' => ['Sarajevo', 'Banja Luka', 'Zenica', 'Tuzla', 'Mostar', 'Bihać', 'Ilidža', 'Lukavac', 'Bugojno', 'Brčko', 'Bijeljina', 'Prijedor', 'Trebinje', 'Travnik', 'Doboj'],
            'BB' => ['Bridgetown'],
            'BD' => ['Dhaka', 'Chattogram', 'Gazipur', 'Khulna', 'Rangpur', 'Rajshahi', 'Comilla', 'Pallabi', 'Mirpur Model Thana', 'Mohammadpur', 'Hāthazāri', 'Bāndarban', 'Shibganj', 'Natore', 'Kafrul'],
            'BE' => ['Brussels', 'Antwerp', 'Gent', 'Charleroi', 'Liège', 'Anderlecht', 'Schaerbeek', 'Brugge', 'Namur', 'Leuven', 'Molenbeek-Saint-Jean', 'Mons', 'Ixelles', 'Uccle', 'Deurne'],
            'BF' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Saaba', 'Ouahigouya', 'Kaya', 'Banfora', 'Pouytenga', 'Houndé', 'Fada N\'gourma', 'Nioko I', 'Dédougou', 'Tenkodogo', 'Djibo', 'Kongoussi'],
            'BG' => ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Stara Zagora', 'Ruse', 'Pleven', 'Sliven', 'Pernik', 'Shumen', 'Dobrich', 'Blagoevgrad', 'Haskovo', 'Yambol', 'Veliko Tŭrnovo'],
            'BH' => ['Al Muharraq', 'Manama', 'Madīnat Ḩamad', 'Ar Rifā‘', 'Sitrah', 'Jidd Ḩafş', 'Dār Kulayb', 'Madīnat ‘Īsá'],
            'BI' => ['Bujumbura', 'Gitega', 'Ngozi', 'Mpanda', 'Rumonge', 'Cibitoke', 'Kayanza', 'Cendajuru', 'Bubanza', 'Vyanda', 'Zanandore', 'Gatumba', 'Karusi', 'Kirundo'],
            'BJ' => ['Cotonou', 'Abomey-Calavi', 'Porto-Novo', 'Parakou', 'Godomè', 'Abomey', 'Djougou', 'Bohicon', 'Ekpé', 'Nikki', 'Malanville', 'Kandi', 'Kérou', 'Natitingou', 'Pobé'],
            'BL' => ['Gustavia'],
            'BM' => ['Hamilton'],
            'BN' => ['Bandar Seri Begawan', 'Sengkurong', 'Mentiri', 'Kuala Belait', 'Seria', 'Tutong', 'Serasa', 'Liang'],
            'BO' => ['La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Sucre', 'Oruro', 'Sacaba', 'Quillacollo', 'Tarija', 'Potosí', 'Riberalta', 'Montero', 'Viacha', 'Trinidad', 'Yacuiba', 'Tiquipaya'],
            'BQ' => ['Kralendijk'],
            'BR' => ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'Fortaleza', 'Manaus', 'Brasília', 'Curitiba', 'Recife', 'Goiânia', 'Belém', 'Porto Alegre', 'Guarulhos', 'Maceió', 'Campinas'],
            'BS' => ['Nassau', 'Lucaya', 'Freeport', 'Killarney'],
            'BT' => ['Thimphu', 'Phuntsholing', 'Tsirang', 'Punākha'],
            'BW' => ['Gaborone', 'Francistown', 'Mogoditshane', 'Maun', 'Molepolole', 'Serowe', 'Tlokweng', 'Palapye', 'Mochudi', 'Mahalapye', 'Kanye', 'Selebi-Phikwe', 'Letlhakane', 'Ramotswa', 'Lobatse'],
            'BY' => ['Minsk', 'Homyel\'', 'Hrodna', 'Vitebsk', 'Mahilyow', 'Brest', 'Bobruysk', 'Baranovichi', 'Barysaw', 'Pinsk', 'Mazyr', 'Lida', 'Orsha', 'Soligorsk', 'Novopolotsk'],
            'BZ' => ['Belize City', 'San Ignacio', 'San Pedro', 'Orange Walk', 'Belmopan'],
            'CA' => ['Toronto', 'Montréal', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Mississauga', 'Vancouver', 'Brampton', 'Hamilton', 'Surrey', 'Québec', 'Halifax', 'Laval', 'London'],
            'CC' => ['West Island'],
            'CD' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Bukavu', 'Kolwezi', 'Likasi', 'Tshikapa', 'Kikwit', 'Masina', 'Mbandaka', 'Goma', 'Matadi', 'Uvira'],
            'CF' => ['Bangui', 'Bimbo', 'Bégoua', 'Carnot', 'Berbérati', 'Bambari', 'Bouar', 'Bossangoa', 'Kaga-Bandoro', 'Bangassou', 'Paoua', 'Bria', 'Kouango', 'Bocaranga', 'Baboua'],
            'CG' => ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Kayes', 'Impfondo', 'Ouesso', 'Owando', 'Sibiti', 'Loutété', 'Bouansa', 'Gamboma', 'Loandjili', 'Mossaka', 'Mindouli'],
            'CH' => ['Zürich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Luzern', 'Sankt Gallen', 'Lugano', 'Biel/Bienne', 'Zürich (Kreis 11)', 'Zürich (Kreis 3)', 'Zürich (Kreis 9)', 'Thun', 'Bellinzona'],
            'CI' => ['Abidjan', 'Abobo', 'Bouaké', 'Korhogo', 'Daloa', 'Koumassi', 'San-Pédro', 'Gagnoa', 'Yamoussoukro', 'Sinfra', 'Man', 'Marcory', 'Bondoukou', 'Dabou', 'Divo'],
            'CK' => ['Avarua'],
            'CL' => ['Santiago', 'Puente Alto', 'Maipú', 'Antofagasta', 'Viña del Mar', 'Valparaíso', 'Ñuñoa', 'San Bernardo', 'Puerto Montt', 'Arica', 'Peñalolén', 'Temuco', 'Concepción', 'Rancagua', 'Quilicura'],
            'CM' => ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Maroua', 'Ngaoundéré', 'Kumba', 'Nkongsamba', 'Buea', 'Kousséri', 'Bertoua', 'Limbe', 'Foumban', 'Kumbo', 'Edéa'],
            'CN' => ['Shanghai', 'Beijing', 'Shenzhen', 'Guangzhou', 'Chengdu', 'Tianjin', 'Wuhan', 'Dongguan', 'Xi’an', 'Nanjing', 'Hangzhou', 'Foshan', 'Chongqing', 'Wuzhong', 'Qingdao'],
            'CO' => ['Bogotá', 'Cali', 'Medellín', 'Barranquilla', 'Kennedy', 'Cartagena', 'Cúcuta', 'Soacha', 'Bucaramanga', 'Ibagué', 'Santa Marta', 'Montería', 'Valledupar', 'Pereira', 'Manizales'],
            'CR' => ['San José', 'Limón', 'San Francisco', 'Alajuela', 'Liberia', 'Paraíso', 'Puntarenas', 'San Isidro', 'Curridabat', 'San Vicente', 'San Vicente de Moravia', 'San José', 'Purral', 'Turrialba', 'San Miguel'],
            'CU' => ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo', 'Santa Clara', 'Almendares', 'Diez de Octubre', 'Arroyo Naranjo', 'Mantilla', 'Las Tunas', 'Bayamo', 'Boyeros', 'Pinar del Río', 'Cienfuegos'],
            'CV' => ['Praia', 'Mindelo', 'Espargos', 'Assomada'],
            'CW' => ['Willemstad', 'Bandariba'],
            'CX' => ['Flying Fish Cove'],
            'CY' => ['Nicosia', 'Limassol', 'Larnaca', 'Stróvolos', 'Famagusta', 'Káto Lakatámeia', 'Paphos', 'Kyrenia', 'Mórfou', 'Káto Polemídia', 'Aradíppou', 'Aglantziá', 'Égkomi', 'Protaras', 'Germasógeia'],
            'CZ' => ['Prague', 'Brno', 'Ostrava', 'Pilsen', 'Liberec', 'Olomouc', 'České Budějovice', 'Hradec Králové', 'Ústí nad Labem', 'Pardubice', 'Brno střed', 'Havířov', 'Zlín', 'Kladno', 'Most'],
            'DE' => ['Berlin', 'Hamburg', 'Munich', 'Köln', 'Frankfurt am Main', 'Düsseldorf', 'Stuttgart', 'Essen', 'Dortmund', 'Dresden', 'Bremen', 'Nuremberg', 'Hannover', 'Leipzig', 'Duisburg'],
            'DJ' => ['Djibouti', 'Balbala', 'Ali Sabih', 'Dikhil', 'Tadjoura', 'Arta', 'Obock'],
            'DK' => ['Copenhagen', 'Århus', 'Odense', 'Aalborg', 'Frederiksberg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Hvidovre', 'Klinteby Frihed', 'Avedøre', 'Roskilde', 'Herning'],
            'DM' => ['Roseau'],
            'DO' => ['Santo Domingo', 'Santiago de los Caballeros', 'Santo Domingo Oeste', 'Santo Domingo Este', 'San Pedro de Macorís', 'La Romana', 'Bella Vista', 'San Cristóbal', 'Puerto Plata', 'San Francisco de Macorís', 'Salvaleón de Higüey', 'La Vega', 'Punta Cana', 'Santa Cruz de Barahona', 'Bonao'],
            'DZ' => ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Bab Ezzouar', 'Djelfa', 'Sétif', 'Sidi Bel Abbes', 'Biskra', 'Tébessa', 'El Oued', 'Skikda', 'Tiaret'],
            'EC' => ['Quito', 'Guayaquil', 'Cuenca', 'Santo Domingo de los Colorados', 'Ambato', 'Portoviejo', 'Eloy Alfaro', 'Machala', 'Loja', 'Manta', 'Riobamba', 'Ibarra', 'Esmeraldas', 'Quevedo', 'Latacunga'],
            'EE' => ['Tallinn', 'Lasnamäe', 'Tartu', 'Mustamäe', 'Kesklinn', 'Põhja-Tallinn', 'Narva', 'Haabersti', 'Pärnu', 'Nõmme', 'Kohtla-Järve', 'Kristiine', 'Pirita', 'Viljandi', 'Maardu'],
            'EG' => ['Cairo', 'Alexandria', 'Giza', 'Shubrā al Khaymah', 'Port Said', 'Suez', 'Madīnat an Naşr', 'Al Mansurah', 'Al Maḩallah al Kubrá', 'Tanta', 'Assiut', 'Al Fayyum', 'Al Khuşūş', 'Esna', 'Zagazig'],
            'EH' => ['Laayoune', 'Dakhla', 'Boujdour', 'El Marsa'],
            'ER' => ['Asmara', 'Keren', 'Himora', 'Massawa', 'Assab', 'Mendefera', 'Barentu'],
            'ES' => ['Madrid', 'Barcelona', 'Valencia', 'Zaragoza', 'Sevilla', 'Málaga', 'Murcia', 'Palma', 'Las Palmas de Gran Canaria', 'Alicante', 'Bilbao', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón'],
            'ET' => ['Addis Ababa', 'Jijiga', 'Gonder', 'Mek\'ele', 'Nazrēt', 'Warder', 'Awasa', 'Bahir Dar', 'Dire Dawa', 'Dessie', 'Jimma', 'Shashamane', 'Bishoftu', 'Sodo', 'Arba Minch'],
            'FI' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'East Helsinki', 'Jyväskylä', 'Kuopio', 'Lahti', 'Pori', 'Joensuu', 'Kouvola', 'Lappeenranta', 'Vaasa'],
            'FJ' => ['Nasinu', 'Suva', 'Lautoka', 'Nadi', 'Labasa', 'Lami', 'Sigatoka'],
            'FK' => ['Stanley'],
            'FM' => ['Palikir'],
            'FO' => ['Tórshavn'],
            'FR' => ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Marne La Vallée', 'Strasbourg', 'Bordeaux', 'Montpellier', 'Lille', 'Paris 15 Vaugirard', 'Rennes', 'Reims', 'Le Havre'],
            'GA' => ['Libreville', 'Port-Gentil', 'Franceville', 'Owendo', 'Oyem', 'Moanda', 'Ntoum', 'Lambaréné', 'Mouila', 'Akanda', 'Tchibanga', 'Bitam', 'Koulamoutou', 'Oyam', 'Makokou'],
            'GB' => ['London', 'Birmingham', 'Glasgow', 'Manchester', 'Sheffield', 'Leeds', 'Edinburgh', 'Liverpool', 'Bristol', 'Cardiff', 'Leicester', 'Bradford', 'Belfast', 'Coventry', 'Brent'],
            'GD' => ['Saint George\'s'],
            'GE' => ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Sokhumi', 'Gori', 'Poti', 'Zugdidi', 'Ts’khinvali', 'Stantsiya Novyy Afon', 'Marneuli', 'Khashuri', 'Samtredia', 'Zestaponi', 'Telavi'],
            'GF' => ['Cayenne', 'Matoury', 'Saint-Laurent-du-Maroni', 'Kourou', 'Rémire-Montjoly'],
            'GG' => ['Saint Peter Port'],
            'GH' => ['Kumasi', 'Accra', 'Tamale', 'Takoradi', 'Sekondi', 'Cape Coast', 'Atsiaman', 'Ashaiman', 'Obuase', 'Tema', 'Koforidua', 'Teshi Old Town', 'Sekondi-Takoradi', 'Ho', 'Amanfrom'],
            'GI' => ['Gibraltar'],
            'GL' => ['Nuuk'],
            'GM' => ['Serekunda', 'Brikama', 'Bununka Kunda', 'Sukuta', 'Talinding', 'Faji Kunda', 'Bakau', 'Banjul', 'Nema Kunku', 'Farafenni', 'Bakau New Town', 'Busumbala', 'Lamin', 'Welingara', 'Brufut'],
            'GN' => ['Conakry', 'Camayenne', 'Nzérékoré', 'Kankan', 'Manéah', 'Dubréka', 'Kindia', 'Siguiri', 'Dixinn', 'Kissidougou', 'Kamsar', 'Labé', 'Gueckedou', 'Mamou', 'Coyah'],
            'GP' => ['Les Abymes', 'Baie-Mahault', 'Le Gosier', 'Petit-Bourg', 'Sainte-Anne', 'Le Moule', 'Sainte-Rose', 'Capesterre-Belle-Eau', 'Pointe-à-Pitre', 'Basse-Terre'],
            'GQ' => ['Bata', 'Malabo', 'Ebebiyin', 'Ciudad de la Paz'],
            'GR' => ['Athens', 'Thessaloníki', 'Pátra', 'Piraeus', 'Lárisa', 'Peristéri', 'Irákleion', 'Kallithéa', 'Acharnés', 'Kalamariá', 'Níkaia', 'Glyfáda', 'Volos', 'Ílion', 'Ilioúpoli'],
            'GS' => ['Grytviken'],
            'GT' => ['Guatemala City', 'Villa Nueva', 'Mixco', 'Cobán', 'Quetzaltenango', 'Jalapa', 'Escuintla', 'Villa Canales', 'Jutiapa', 'Chichicastenango', 'San Juan Sacatepéquez', 'Petapa', 'Santa Lucía Cotzumalguapa', 'Chiquimula', 'Coatepeque'],
            'GU' => ['Dededo Village', 'Yigo Village', 'Tamuning-Tumon-Harmon Village', 'Tamuning', 'Mangilao Village', 'Hagåtña'],
            'GW' => ['Bissau', 'Bairro Militar', 'Gabú', 'Contumo', 'Reino de Bandim', 'Missira', 'Bafatá', 'Reino de Antula', 'Quelele', 'Plaque', 'Luanda', 'Sintra-Nema', 'Xitole', 'Belem', 'Santa-Luzia'],
            'GY' => ['Georgetown', 'Linden', 'New Amsterdam'],
            'HK' => ['Hong Kong', 'New Territories', 'Kowloon', 'Hong Kong Island', 'Victoria', 'Tuen Mun', 'Sha Tin', 'Sham Shui Po', 'Wong Tai Sin', 'Kowloon City', 'Tseung Kwan O', 'Kwai Chung', 'Tsuen Wan', 'Tin Shui Wai', 'Tai Po'],
            'HN' => ['Tegucigalpa', 'San Pedro Sula', 'Danlí', 'La Ceiba', 'La Ceiba', 'Puerto Cortez', 'Catacamas', 'Choloma', 'Siguatepeque', 'Olanchito', 'Tocoa', 'El Progreso', 'Santa Cruz de Yojoa', 'Ciudad Choluteca', 'San Pedro de Copán'],
            'HR' => ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Sesvete', 'Pula', 'Slavonski Brod', 'Karlovac', 'Centar', 'Varaždin', 'Šibenik', 'Velika Gorica', 'Vinkovci', 'Sisak'],
            'HT' => ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétionville', 'Port-de-Paix', 'Saint-Marc', 'Croix-des-Bouquets', 'Dessalines', 'Jacmel', 'Cap-Haïtien', 'Léogâne', 'Arcahaie', 'Les Cayes', 'Tigwav', 'Jérémie'],
            'HU' => ['Budapest', 'Pest', 'Buda', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Budapest XI. kerület', 'Zugló', 'Győr', 'Budapest III. kerület', 'Nyíregyháza', 'Budapest XIII. kerület', 'Kecskemét', 'Székesfehérvár'],
            'ID' => ['Jakarta', 'Surabaya', 'Bekasi', 'Bandung', 'Medan', 'Depok', 'Tangerang', 'Palembang', 'Semarang', 'Makassar', 'South Tangerang', 'Batam', 'Jepara', 'Pekanbaru', 'Bandar Lampung'],
            'IE' => ['Dublin', 'South Dublin', 'Cork', 'Limerick', 'Galway', 'Tallaght', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Navan', 'Bray', 'Dún Laoghaire', 'Ennis', 'Carlow'],
            'IL' => ['Jerusalem', 'Tel Aviv', 'West Jerusalem', 'Haifa', 'Rishon LeTsiyyon', 'Petaẖ Tiqva', 'Netanya', 'Ashdod', 'Bnei Brak', 'H̱olon', 'Beersheba', 'Ramat Gan', 'Reẖovot', 'Ashkelon', 'Bat Yam'],
            'IM' => ['Douglas'],
            'IN' => ['Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Kanpur', 'Navi Mumbai', 'Lucknow', 'Nagpur', 'Coimbatore'],
            'IQ' => ['Baghdad', 'Al Mawşil al Jadīdah', 'Al Başrah al Qadīmah', 'Mosul', 'Erbil', 'Basrah', 'Karbala', 'Sadr City', 'Kirkuk', 'Abū Ghurayb', 'Sulaymaniyah', 'Nasiriyah', 'Najaf', 'Al Hillah', 'Abū al-Kahṣīb'],
            'IR' => ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Qom', 'Ahvaz', 'Kermanshah', 'Rasht', 'Kerman', 'Orūmīyeh', 'Zahedan', 'Hamadān', 'Arāk'],
            'IS' => ['Reykjavík', 'Kópavogur', 'Hafnarfjörður', 'Reykjanesbær', 'Akureyri', 'Keflavík'],
            'IT' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Verona', 'Messina', 'Trieste', 'Padua', 'Brescia'],
            'JE' => ['Saint Helier'],
            'JM' => ['Kingston', 'New Kingston', 'Spanish Town', 'Portmore', 'Montego Bay', 'Mandeville', 'May Pen', 'Ocho Rios', 'Old Harbour', 'Linstead', 'Half Way Tree', 'Barrett Town', 'Savanna-la-Mar'],
            'JO' => ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Ḩayy Khildā', 'Khuraybat as Sūq', 'Wādī as Sīr', 'Ar Ramthā', 'Ṣuwayliḥ', '‘Ajlūn', 'As Salţ', 'Aqaba', 'Rukban', 'Marj Al Hamam', 'Mādabā'],
            'JP' => ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kawasaki', 'Kobe', 'Kyoto', 'Saitama', 'Hiroshima', 'Sendai', 'Chiba', 'Kitakyushu', 'Setagaya'],
            'KE' => ['Nairobi', 'Kakamega', 'Mombasa', 'Nakuru', 'Ruiru', 'Eldoret', 'Kisumu', 'Kikuyu', 'Thika', 'Naivasha', 'Karuri', 'Karuri', 'Matuga', 'Mwala', 'Ongata Rongai'],
            'KG' => ['Bishkek', 'Osh', 'Manas', 'Karakol', 'Tokmok', 'Uzgen', 'Kara-Balta', 'Balykchy', 'Naryn', 'Bazar-Korgon', 'Talas', 'Razzakov', 'Kyzyl-Kyya', 'Suzak', 'Batken'],
            'KH' => ['Phnom Penh', 'Takeo', 'Siem Reap', 'Battambang', 'Paoy Paet', 'Dangkao', 'Kampong Chhnang', 'Sihanoukville', 'Preaek Prasab', 'Kampong Cham', 'Anlong Veaeng', 'Pursat', 'Ta Khmau', 'Phumĭ Yoŭl Toŭng', 'Phumĭ Véal Srê'],
            'KI' => ['Tarawa'],
            'KM' => ['Moroni', 'Moutsamoudou', 'Fomboni'],
            'KN' => ['Basseterre'],
            'KP' => ['Pyongyang', 'Hamhŭng', 'Namp’o', 'Sunch’ŏn', 'Hŭngnam', 'Kaesŏng', 'Wŏnsan', 'Chongjin', 'Man’gyŏngdae-ri', 'Kaech’ŏn', 'Sariwŏn-si', 'Sinŭiju', 'Tŏkch’ŏn', 'Haeju', 'Kanggye'],
            'KR' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Goyang-si', 'Changwon', 'Seongnam-si', 'Cheongju-si', 'Bucheon-si', 'Cheonan', 'Hwaseong-si'],
            'KW' => ['Al Aḩmadī', 'Ḩawallī', 'As Sālimīyah', 'Şabāḩ as Sālim', 'Al Farwānīyah', 'Al Faḩāḩīl', 'Kuwait City', 'Ar Rumaythīyah', 'Ar Riqqah', 'Salwá', 'Al Manqaf', 'Ar Rābiyah', 'Bayān', 'Al Jahrā’', 'Al Finţās'],
            'KY' => ['George Town', 'West Bay'],
            'KZ' => ['Almaty', 'Astana', 'Shymkent', 'Aktobe', 'Karagandy', 'Taraz', 'Kyzylorda', 'Oral', 'Pavlodar', 'Ust-Kamenogorsk', 'Semey', 'Atyrau', 'Turkistan', 'Kostanay', 'Petropavl'],
            'LA' => ['Vientiane', 'Savannakhet', 'Thakhèk', 'Pakse', 'Ban Khoan', 'Xam Nua', 'Luang Prabang', 'Muang Phônsavan', 'Ban Xénô', 'Muang Xay', 'Vang Vieng', 'Muang Sing', 'Pakxan', 'Ban Laongam', 'Sekong'],
            'LB' => ['Beirut', 'Ra’s Bayrūt', 'Tripoli', 'Sidon', 'Tyre', 'Aley', 'Nabatîyé et Tahta', 'Habboûch', 'Jounieh', 'Zahlé', 'Aarsâl', 'Ghazieh', 'Baalbek', 'Chmistâr', 'En Nâqoûra'],
            'LC' => ['Gros Islet', 'Castries'],
            'LI' => ['Vaduz'],
            'LK' => ['Colombo', 'Dehiwala-Mount Lavinia', 'Maharagama', 'Jaffna', 'Moratuwa', 'Negombo', 'Pita Kotte', 'Sri Jayewardenepura Kotte', 'Kandy', 'Trincomalee', 'Kalmunai', 'Galle', 'Point Pedro', 'Batticaloa', 'Katunayaka'],
            'LR' => ['Monrovia', 'Gbarnga', 'Buchanan', 'Ganta', 'Kakata', 'Zwedru', 'Harbel', 'Harper', 'Pleebo City', 'Foya Kamara', 'New Yekepa', 'Voinjama', 'Tubmanburg', 'Saclepea', 'Greenville'],
            'LS' => ['Maseru', 'Maputsoe', 'Mohale\'s Hoek', 'Mafeteng', 'Hlotse', 'Butha-Buthe', 'Mabote', 'Quthing', 'Teyateyaneng', 'Qacha’s Nek', 'Thaba-Tseka'],
            'LT' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Dainava (Kaunas)', 'Alytus', 'Šilainiai', 'Eiguliai', 'Antakalnis', 'Fabijoniškės', 'Naujoji Vilnia', 'Šeškinė', 'Marijampolė', 'Naujininkai'],
            'LU' => ['Luxembourg', 'Esch-sur-Alzette', 'Dudelange'],
            'LV' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Ogre', 'Jēkabpils', 'Mārupe', 'Salaspils', 'Dārzciems', 'Tukums', 'Cēsis'],
            'LY' => ['Tripoli', 'Benghazi', 'Misratah', 'Zliten', 'Al Khums', 'Az Zāwīyah', 'Zawiya', 'Janzūr', 'Sabha', 'Tobruk', 'Ajdabiya', 'Al Ajaylat', 'Al Bayḑā’', 'Al Jadīd', 'Sirte'],
            'MA' => ['Casablanca', 'Rabat', 'Fes', 'Tangier', 'Marrakesh', 'Salé', 'Agadir', 'Meknes', 'Oujda', 'Kenitra', 'Tétouan', 'Al Hoceïma', 'Temara', 'Safi', 'Mohammedia'],
            'MC' => ['Monaco', 'Monte-Carlo'],
            'MD' => ['Chisinau', 'Tiraspol', 'Bălţi', 'Bender', 'Rîbniţa', 'Cahul', 'Ungheni', 'Soroca', 'Durleşti', 'Orhei', 'Dubăsari', 'Comrat', 'Edineţ', 'Ceadîr-Lunga', 'Căuşeni'],
            'ME' => ['Podgorica', 'Nikšić', 'Herceg Novi', 'Pljevlja', 'Budva', 'Bar', 'Bijelo Polje', 'Cetinje'],
            'MF' => ['Marigot'],
            'MG' => ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa', 'Toliara', 'Antsiranana', 'Sambava', 'Imerintsiatosika', 'Antalaha', 'Tôlanaro', 'Antanifotsy', 'Ambovombe', 'Ambilobe', 'Ambanja'],
            'MH' => ['Majuro', 'Dalap-Uliga-Dorrit'],
            'MK' => ['Skopje', 'Kumanovo', 'Prilep', 'Bitola', 'Čair', 'Tetovo', 'Kisela Voda', 'Veles', 'Gostivar', 'Shtip', 'Centar Župa', 'Ohrid', 'Gjorče Petro', 'Kavadarci', 'Struga'],
            'ML' => ['Bamako', 'Sikasso', 'Koutiala', 'Ségou', 'Kayes', 'Mopti', 'Kalaban Koro', 'Gao', 'Kati', 'San', 'Bougouni', 'Timbuktu', 'Kita', 'Dialakorodji', 'Koulikoro'],
            'MM' => ['Yangon', 'Mandalay', 'Nay Pyi Taw', 'Hlaingthaya', 'Mawlamyine', 'Kalemyo', 'Insein', 'Bago', 'Amarapura', 'Pathein', 'Yawnghwe', 'Monywa', 'Kyaukpyu', 'Sittwe', 'Meiktila'],
            'MN' => ['Ulan Bator', 'Erdenet', 'Darhan', 'Choibalsan', 'Nalayh', 'Mörön', 'Bayanhongor', 'Ulaangom', 'Khovd', 'Arvayheer', 'Ölgii', 'Bogd', 'Dalandzadgad', 'Sühbaatar', 'Undurkhaan'],
            'MO' => ['Macau', 'Taipa', 'Sé', 'Luhuan', 'Zhuojiacun', 'Lai Chi Van'],
            'MP' => ['Saipan'],
            'MQ' => ['Fort-de-France', 'Le Lamentin', 'Le Robert', 'Sainte-Marie', 'Le François', 'Ducos', 'Saint-Joseph', 'La Trinité'],
            'MR' => ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Dar Naim', 'Néma', 'Mbera', 'Ksar', 'Kaédi', 'Zouérat', 'Tevragh Zeina', 'Bougadoum', 'Sélibaby', 'Atar', 'Ayoun El Atrous', 'Guerou'],
            'MS' => ['Brades', 'Plymouth'],
            'MT' => ['San Pawl il-Baħar', 'Birkirkara', 'Mosta', 'Sliema', 'Qormi', 'Żabbar', 'Valletta'],
            'MU' => ['Port Louis', 'Vacoas', 'Beau Bassin-Rose Hill', 'Curepipe', 'Quatre Bornes', 'Triolet', 'Goodlands', 'Bel Air Rivière Sèche', 'Bambous', 'Centre de Flacq', 'Mahébourg', 'Saint Pierre', 'Le Hochet', 'Baie du Tombeau'],
            'MV' => ['Male'],
            'MW' => ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Karonga', 'Kasungu', 'Mangochi', 'Salima', 'Liwonde', 'Balaka', 'Dedza', 'Nkhotakota', 'Mchinji', 'Nsanje', 'Mzimba'],
            'MX' => ['Mexico City', 'Tijuana', 'Iztapalapa', 'Puebla', 'Ecatepec de Morelos', 'Santiago de Querétaro', 'León de los Aldama', 'Ciudad Juárez', 'Zapopan', 'Guadalajara', 'Mérida', 'Gustavo Adolfo Madero', 'Monterrey', 'Ciudad Nezahualcoyotl', 'Mexicali'],
            'MY' => ['Kuala Lumpur', 'Johor Bahru', 'Kampung Baru Subang', 'Petaling Jaya', 'Ipoh', 'Shah Alam', 'Subang Jaya', 'Bukit Rahman Putra', 'Pelentong', 'Malacca', 'Iskandar Puteri', 'Kota Bharu', 'Kuantan', 'Kota Kuala Muda', 'Sungai Petani'],
            'MZ' => ['Maputo', 'Matola', 'Nampula', 'Beira', 'Chimoio', 'Tete', 'Quelimane', 'Lichinga', 'Nacala', 'Pemba', 'Mocuba', 'Gurúè', 'Xai-Xai', 'Maxixe', 'Mandimba'],
            'NA' => ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund', 'Oshakati', 'Rehoboth', 'Katima Mulilo', 'Otjiwarongo', 'Ondangwa', 'Okahandja', 'Grootfontein', 'Ongwediva', 'Keetmanshoop', 'Helao Nafidi', 'Tsumeb'],
            'NC' => ['Nouméa', 'Mont-Dore', 'Dumbéa'],
            'NE' => ['Niamey', 'Maradi', 'Zinder', 'Tahoua', 'Agadez', 'Arlit', 'Alaghsas', 'Birni N Konni', 'Dosso', 'Gaya', 'Tessaoua', 'Diffa', 'Dogondoutchi', 'Méhana', 'Dakoro'],
            'NF' => ['Kingston'],
            'NG' => ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Kaduna', 'Benin City', 'Onitsha', 'Aba', 'Maiduguri', 'Ilorin', 'Sokoto', 'Jos', 'Zaria', 'Enugu'],
            'NI' => ['Managua', 'León', 'Masaya', 'Chinandega', 'Matagalpa', 'Estelí', 'Granada', 'Mateare', 'Jinotega', 'El Viejo', 'Nueva Guinea', 'Tipitapa', 'Juigalpa', 'Ciudad Sandino', 'Bluefields'],
            'NL' => ['Rotterdam', 'Amsterdam', 'The Hague', 'Utrecht', 'Groningen', 'Eindhoven', 'Tilburg', 'Breda', 'Nijmegen', 'Almere Stad', 'Haarlem', 'Arnhem', '\'s-Hertogenbosch', 'Enschede', 'Zaanstad'],
            'NO' => ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Kristiansand', 'Drammen', 'Lillestrøm', 'Sandnes', 'Fredrikstad', 'Sandefjord', 'Asker', 'Sarpsborg', 'Tønsberg', 'Ålesund', 'Skien'],
            'NP' => ['Kathmandu', 'Pokhara', 'Bharatpur', 'Pātan', 'Birgañj', 'Biratnagar', 'Dhangaḍhi̇̄', 'Hetauda', 'Janakpur', 'Butwāl', 'Dharān', 'Nepalgunj', 'Birendranagar', 'Madhyapur Thimi', 'Lahān'],
            'NR' => ['Yaren'],
            'NU' => ['Alofi'],
            'NZ' => ['Auckland', 'Christchurch', 'Wellington', 'Manukau City', 'North Shore', 'Hamilton', 'Tauranga', 'Dunedin', 'Lower Hutt', 'Palmerston North', 'New Plymouth', 'Hastings', 'Napier', 'Rotorua', 'Porirua'],
            'OM' => ['Muscat', 'Seeb', 'Bawshar', '‘Ibrī', 'Şalālah', 'Şaḩam', 'Rustaq', 'Sohar', 'As Suwayq', 'Barkā’', 'Samā’il', 'Al Buraymī', 'Nizwá', 'Sur', 'Qurayyāt'],
            'PA' => ['Panama City', 'San Miguelito', 'Juan Díaz', 'David', 'Colón', 'Arraiján', 'Las Cumbres', 'La Chorrera', 'Pedregal', 'Tocumen', 'Santiago de Veraguas', 'Parque Lefevre', 'Chilibre', 'Cativá', 'Río Abajo'],
            'PE' => ['Lima', 'Callao', 'Arequipa', 'Trujillo', 'Piura', 'Chiclayo', 'Huancayo', 'Cusco', 'Iquitos', 'Pucallpa', 'Chimbote', 'Tacna', 'Ica', 'Santiago de Surco', 'Juliaca'],
            'PF' => ['Faaa', 'Papeete', 'Punaauia'],
            'PG' => ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Popondetta', 'Madang', 'Kokopo', 'Mendi', 'Kimbe', 'Goroka', 'Wewak', 'Bulolo', 'Daru'],
            'PH' => ['Quezon City', 'Davao', 'Caloocan', 'Manila', 'Taguig', 'Budta', 'Malingao', 'Zamboanga', 'Cebu City', 'Antipolo', 'Pasig City', 'Cagayan de Oro', 'Valenzuela', 'General Santos', 'Paranaque City'],
            'PK' => ['Lahore', 'Karachi', 'Peshawar', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 'Multan', 'Hyderabad', 'Quetta', 'Bannu', 'Sargodha', 'Sialkot', 'Bahawalpur', 'Arifwala', 'Dera Ismail Khan'],
            'PL' => ['Warsaw', 'Kraków', 'Wrocław', 'Łódź', 'Poznań', 'Gdańsk', 'Szczecin', 'Lublin', 'Bydgoszcz', 'Białystok', 'Katowice', 'Gdynia', 'Częstochowa', 'Sosnowiec', 'Radom'],
            'PM' => ['Saint-Pierre'],
            'PN' => ['Adamstown'],
            'PR' => ['San Juan', 'Bayamón', 'Carolina', 'Ponce', 'Arecibo', 'Caguas', 'Guaynabo', 'Trujillo Alto', 'Mayagüez', 'Fajardo', 'Levittown', 'Vega Baja', 'Cataño', 'Barceloneta', 'Guayama'],
            'PS' => ['East Jerusalem', 'Gaza', 'Khān Yūnis', 'Jabālyā', 'Hebron', 'Nablus', 'Rafaḩ', 'Dayr al Balaḩ', 'Bayt Lāhyā', 'Battir', 'Ţūlkarm', 'Ramallah', 'Qalqīlyah', 'Yaţţā', 'Ma‘ale Adummim'],
            'PT' => ['Lisbon', 'Porto', 'Braga', 'Amadora', 'Coimbra', 'Leiria', 'Setúbal', 'Funchal', 'Viseu', 'Queluz', 'Cacém', 'Aveiro', 'Vila Nova de Gaia', 'Faro', 'Algueirão'],
            'PW' => ['Ngerulmud'],
            'PY' => ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Capiatá', 'Lambaré', 'Fernando de la Mora', 'Limpio', 'Nemby', 'Pedro Juan Caballero', 'Encarnación', 'Mariano Roque Alonso', 'Itauguá', 'Villa Elisa', 'Villa Hayes', 'Caacupé'],
            'QA' => ['Doha', 'Ar Rayyān', 'Lusail', 'Al Maţār al ‘Atīq', 'Al Manşūrah', 'Az̧ Z̧a‘āyin', 'Madīnat Khalīfah', 'An Najmah', 'Al ‘Unayzah', 'Umm Ghuwaylīnah', 'As Sadd', 'Farīj Kulayb', 'Farīj al Amīr', 'Umm Şalāl Muḩammad', 'Mu‘aydhir Rawḑat Rāshid'],
            'RE' => ['Saint-Denis', 'Saint-Paul', 'Saint-Pierre', 'Le Tampon', 'Saint-André', 'Saint-Louis', 'Saint-Joseph', 'Saint-Benoît', 'La Possession', 'Saint-Leu', 'Sainte-Marie', 'Le Port', 'Piton Saint-Leu', 'Sainte-Suzanne'],
            'RO' => ['Bucharest', 'Sector 3', 'Iaşi', 'Sector 6', 'Constanţa', 'Sector 2', 'Sector 4', 'Cluj-Napoca', 'Sector 5', 'Braşov', 'Timişoara', 'Craiova', 'Sector 1', 'Galaţi', 'Târgu Mureş'],
            'RS' => ['Belgrade', 'Niš', 'Novi Sad', 'Zemun', 'Kragujevac', 'Čačak', 'Subotica', 'Leskovac', 'Novi Pazar', 'Kraljevo', 'Zrenjanin', 'Pančevo', 'Kruševac', 'Užice', 'Smederevo'],
            'RU' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhniy Novgorod', 'Kazan', 'Chelyabinsk', 'Omsk', 'Samara', 'Rostov-on-Don', 'Ufa', 'Krasnoyarsk', 'Voronezh', 'Volgograd', 'Perm'],
            'RW' => ['Kigali', 'Gisenyi', 'Musanze', 'Nyagatare', 'Gitarama', 'Muhanga', 'Butare', 'Kibuye', 'Rwamagana', 'Kibungo', 'Cyangugu', 'Shyorongi', 'Byumba', 'Ndera', 'Kirambo'],
            'SA' => ['Jeddah', 'Riyadh', 'Makkah', 'Madinah', 'Dammam', 'Sulţānah', 'Buraydah', 'Ta’if', 'Tabuk', 'Ha\'il', 'Najrān', 'Al Kharj', 'Khamis Mushait', 'Al Hufūf', 'Al Mubarraz'],
            'SB' => ['Honiara', 'Panatina', 'Nggosi', 'Tandai', 'Kola\'a', 'Vura', 'Malango'],
            'SC' => ['Victoria'],
            'SD' => ['Khartoum', 'Omdurman', 'Khartoum North', 'Nyala', 'Port Sudan', 'Kassala', 'El Obeid', 'Al Qadarif', 'Kosti', 'Wad Medani', 'El Daein', 'El Fasher', 'Singa', 'Ad-Damazin', 'Al-Junaynah'],
            'SE' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Örebro', 'Sollentuna', 'Umeå', 'Västerås', 'Södermalm', 'Jönköping', 'Helsingborg', 'Norrköping', 'Huddinge', 'Lund'],
            'SG' => ['Singapore', 'Ulu Bedok', 'Bedok New Town', 'Sengkang New Town', 'Tampines Estate', 'Jurong Town', 'Tampines New Town', 'Woodlands', 'Jurong West', 'Yishun New Town', 'Hougang New Town', 'Punggol', 'Choa Chu Kang New Town', 'Ang Mo Kio New Town', 'Bukit Batok New Town'],
            'SH' => ['Jamestown'],
            'SI' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Novo Mesto', 'Velenje', 'Ptuj', 'Trbovlje'],
            'SJ' => ['Longyearbyen'],
            'SK' => ['Bratislava', 'Košice', 'Petržalka', 'Nitra', 'Prešov', 'Žilina', 'Banská Bystrica', 'Trnava', 'Trenčín', 'Martin', 'Poprad', 'Staré Mesto', 'Prievidza', 'Zvolen', 'Považská Bystrica'],
            'SL' => ['Freetown', 'Kenema', 'Bo', 'Koidu', 'Makeni', 'Waterloo', 'Port Loko', 'Njala', 'Lunsar', 'Goderich', 'Kabala', 'Segbwema', 'Bumpe', 'Mile 91'],
            'SM' => ['San Marino'],
            'SN' => ['Dakar', 'Pikine', 'Touba', 'Guédiawaye', 'Thiès', 'Kaolack', 'Rufisque', 'Mbour', 'Saint-Louis', 'Thiès Nones', 'Rufisque est', 'Ziguinchor', 'Diourbel', 'Tambacounda', 'Louga'],
            'SO' => ['Mogadishu', 'Borama', 'Hargeysa', 'Berbera', 'Kismayo', 'Marka', 'El Dibir', 'Ruqi', 'Baidoa', 'Cabudwaaq', 'Burao', 'Kaambooni', 'Gebiley', 'Bosaso', 'Beled Hawo'],
            'SR' => ['Paramaribo', 'Blauwgrond', 'Latour', 'Pontbuiten', 'Rainville', 'Flora', 'Welgelegen', 'Lelydorp', 'Munder Buiten', 'Beekhuizen', 'Weg naar Zee', 'Tammenga'],
            'SS' => ['Juba', 'Winejok', 'Yei', 'Malakal', 'Wau', 'Kuacjok', 'Pajok', 'Gogrial', 'Yambio', 'Aweil', 'Rumbek', 'Bor', 'Torit', 'Leer', 'Tonj'],
            'ST' => ['São Tomé'],
            'SV' => ['San Salvador', 'Soyapango', 'San Miguel', 'Santa Ana', 'Mejicanos', 'Santa Tecla', 'Apopa', 'Delgado', 'Sonsonate', 'San Marcos', 'Usulután', 'Cojutepeque', 'Cuscatancingo', 'San Vicente', 'Zacatecoluca'],
            'SX' => ['Philipsburg'],
            'SY' => ['Aleppo', 'Damascus', 'Homs', 'Latakia', 'Ar Raqqah', 'Ḩamāh', 'Ţarţūs', 'Al Ḩasakah', 'Deir ez-Zor', 'Al Qāmishlī', 'Al Bāb', 'Idlib', 'Dūmā', 'al-Yarmūk', 'Jaramānā'],
            'SZ' => ['Manzini', 'Mbabane', 'Lobamba'],
            'TC' => ['Providenciales', 'Cockburn Town'],
            'TD' => ['N\'Djamena', 'Moundou', 'Abéché', 'Sarh', 'Kelo', 'Am Timan', 'Doba', 'Pala', 'Bongor', 'Goz Beida', 'Koumra', 'Mongo', 'Bol', 'Mao', 'Déressia'],
            'TF' => ['Port-aux-Français'],
            'TG' => ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Kpalimé', 'Bassar', 'Dapaong', 'Tsévié', 'Aného', 'Mango', 'Anié', 'Notsé', 'Sinkassé', 'Tchamba', 'Sotouboua'],
            'TH' => ['Bangkok', 'Samut Prakan', 'Mueang Nonthaburi', 'Chon Buri', 'Phra Pradaeng', 'Bang Khae', 'Hat Yai', 'Pak Kret', 'Sai Mai', 'Si Racha', 'Latkrabang', 'Watthana', 'Khlong Sam Wa', 'Bang Khun Thian', 'Lat Krabang'],
            'TJ' => ['Dushanbe', 'Isfara', 'Istaravshan', 'Kŭlob', 'Konibodom', 'Khujand', 'Bokhtar', 'Qayroqqum', 'Vahdat', 'Tursunzoda', 'Buston', 'Panjakent', 'Zarhalol', 'Khorugh', 'Muchun'],
            'TL' => ['Dili', 'Maliana', 'Suai', 'Likisá', 'Aileu', 'Lospalos', 'Atsabe', 'Maubara', 'Baukau', 'Venilale'],
            'TM' => ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Türkmenbaşy', 'Balkanabat', 'Bayramaly', 'Tejen', 'Gyzylarbat', 'Magdanly', 'Arkadag', 'Boldumsaz', 'Abadan', 'Yolöten', 'Bäherden'],
            'TN' => ['Tunis', 'Sfax', 'Sousse', 'Sukrah', 'Kairouan', 'Bizerte', 'Sakiet ed Daier', 'El Mourouj', 'Aryanah', 'Gabès', 'Sejoumi', 'Hammamet', 'Sakiet ez Zit', 'Gafsa', 'La Gazelle'],
            'TO' => ['Nuku‘alofa'],
            'TR' => ['Istanbul', 'Ankara', 'Bursa', 'İzmir', 'Gaziantep', 'Diyarbakır', 'Adana', 'Kayseri', 'Konya', 'Antalya', 'Esenyurt', 'Eskişehir', 'Çankaya', 'Küçükçekmece', 'Erzurum'],
            'TT' => ['Chaguanas', 'Mon Repos', 'San Fernando', 'Port of Spain', 'Rio Claro', 'Arima', 'Marabella', 'Diego Martin', 'Laventille', 'Point Fortin', 'Tunapuna', 'Scarborough', 'Sangre Grande', 'Paradise'],
            'TV' => ['Funafuti'],
            'TW' => ['Taipei', 'New Taipei City', 'Taichung', 'Kaohsiung', 'Tainan', 'Banqiao', 'Taoyuan', 'Hsinchu', 'Keelung', 'Fengshan', 'Neihu', 'Chiayi City', 'Yongkang', 'Chang-hua', 'Changhua'],
            'TZ' => ['Dar es Salaam', 'Mwanza', 'Dodoma', 'Zanzibar', 'Arusha', 'Mbeya', 'Morogoro', 'Kahama', 'Tanga', 'Geita', 'Tabora', 'Sumbawanga', 'Songea', 'Kibaha', 'Bariadi'],
            'UA' => ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Lviv', 'Zaporizhzhya', 'Kryvyy Rih', 'Sevastopol', 'Mykolayiv', 'Vinnytsya', 'Saltivka', 'Luhansk', 'Desna', 'Dniprovskyi'],
            'UG' => ['Kampala', 'Nansana', 'Kira', 'Bunamwaya', 'Kyengera', 'Mbarara', 'Kasangati', 'Mukono', 'Njeru', 'Gulu', 'Katabi', 'Kajansi', 'Lugazi', 'Hoima', 'Mubende'],
            'US' => ['New York City', 'Los Angeles', 'Brooklyn', 'Chicago', 'Queens', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'Manhattan', 'San Diego', 'The Bronx', 'Dallas', 'Jacksonville', 'Fort Worth'],
            'UY' => ['Montevideo', 'Salto', 'Maldonado', 'Rivera', 'Paysandú', 'Las Piedras', 'Tacuarembó', 'Melo', 'Artigas', 'Mercedes', 'Durazno', 'Minas', 'Florida', 'San José de Mayo', 'Colonia del Sacramento'],
            'UZ' => ['Tashkent', 'Andijon', 'Namangan', 'Samarkand', 'Yunusobod', 'Nukus', 'Fergana', 'Bukhara', 'Qarshi', 'Chilanzar', 'Qo‘qon', 'Marg‘ilon', 'Angren', 'Tirmiz', 'Jizzax'],
            'VA' => ['Vatican City'],
            'VC' => ['Kingstown', 'Calliaqua'],
            'VE' => ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Ciudad Guayana', 'Barcelona', 'Maturín', 'Maracay', 'Ciudad Bolívar', 'Cumaná', 'Barinas', 'Puerto La Cruz', 'Petare', 'Cabimas', 'Turmero'],
            'VG' => ['Road Town'],
            'VI' => ['Saint Croix', 'Charlotte Amalie'],
            'VN' => ['Ho Chi Minh City', 'Hanoi', 'Haiphong', 'Cần Thơ', 'Huế', 'Da Nang', 'Biên Hòa', 'Thanh Hóa', 'Vinh', 'Thuận An', 'Nha Trang', 'Chợ Lớn', 'Bình Thạnh', 'Thủ Đức', 'Qui Nhon'],
            'VU' => ['Port-Vila'],
            'WF' => ['Mata-Utu'],
            'WS' => ['Apia'],
            'XK' => ['Pristina', 'Prizren', 'Mitrovicë', 'Gjakovë', 'Suva Reka', 'Ferizaj', 'Glogovac', 'Gjilan', 'Deçan', 'Pejë', 'Vitina', 'Istok', 'Shtime', 'Podujeva', 'Dragash'],
            'YE' => ['Sanaa', 'Aden', 'Taiz', 'Ibb', 'Al Ḩudaydah', 'Mukalla', 'Dhamār', '‘Amrān', 'Sayyān', 'Zabīd', 'Sa\'dah', 'Bājil', 'Ḩajjah', 'Dhī as Sufāl', 'Al Bayda'],
            'YT' => ['Mamoudzou', 'Koungou', 'Labattoir', 'Kaouéni', 'Mtsapéré', 'Dzaoudzi'],
            'ZA' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Soweto', 'Gqeberha', 'Soshanguve', 'Pietermaritzburg', 'Evaton', 'Benoni', 'Bloemfontein', 'Thembisa', 'East London', 'Vereeniging', 'Boksburg'],
            'ZM' => ['Lusaka', 'Kitwe', 'Ndola', 'Chipata', 'Solwezi', 'Kabwe', 'Chingola', 'Luanshya', 'Kasama', 'Livingstone', 'Mansa', 'Mufulira', 'Chunga', 'Chililabombwe', 'Mongu'],
            'ZW' => ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth', 'Gweru', 'Kwekwe', 'Kadoma', 'Ruwa', 'Chinhoyi', 'Masvingo', 'Norton', 'Marondera', 'Chegutu', 'Zvishavane'],
        ];
    }
}
