<?php

/*
 * This file is part of the PhpNitro package.
 *
 * (c) Ronaldo AWADEME <awademeronaldoo@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Engine\Countries;

/**
 * Country facts (name, capital, continent, calling code, currency) — derived
 * from the mledoze/countries open dataset (ODbL-licensed, see
 * packages/countries/DATA_LICENSE), 194 UN member / independent states.
 * Flag is computed from the ISO 3166-1 alpha-2 code (regional indicator
 * symbols), not stored data — always correct by construction, no lookup table
 * to keep in sync.
 */
final class CountryData
{
    /**
     * @return array<int, array{cca2: string, cca3: string, name: string, nameFr: string, capital: ?string, continent: string, callingCode: string, currency: string}>
     */
    public static function all(): array
    {
        return [
            ['cca2' => 'AF', 'cca3' => 'AFG', 'name' => 'Afghanistan', 'nameFr' => 'Afghanistan', 'capital' => 'Kabul', 'continent' => 'ASIA', 'callingCode' => '+93', 'currency' => 'AFN'],
            ['cca2' => 'AL', 'cca3' => 'ALB', 'name' => 'Albania', 'nameFr' => 'Albanie', 'capital' => 'Tirana', 'continent' => 'EUROPE', 'callingCode' => '+355', 'currency' => 'ALL'],
            ['cca2' => 'DZ', 'cca3' => 'DZA', 'name' => 'Algeria', 'nameFr' => 'Algérie', 'capital' => 'Algiers', 'continent' => 'AFRICA', 'callingCode' => '+213', 'currency' => 'DZD'],
            ['cca2' => 'AD', 'cca3' => 'AND', 'name' => 'Andorra', 'nameFr' => 'Andorre', 'capital' => 'Andorra la Vella', 'continent' => 'EUROPE', 'callingCode' => '+376', 'currency' => 'EUR'],
            ['cca2' => 'AO', 'cca3' => 'AGO', 'name' => 'Angola', 'nameFr' => 'Angola', 'capital' => 'Luanda', 'continent' => 'AFRICA', 'callingCode' => '+244', 'currency' => 'AOA'],
            ['cca2' => 'AG', 'cca3' => 'ATG', 'name' => 'Antigua and Barbuda', 'nameFr' => 'Antigua-et-Barbuda', 'capital' => 'Saint John\'s', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1268', 'currency' => 'XCD'],
            ['cca2' => 'AR', 'cca3' => 'ARG', 'name' => 'Argentina', 'nameFr' => 'Argentine', 'capital' => 'Buenos Aires', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+54', 'currency' => 'ARS'],
            ['cca2' => 'AM', 'cca3' => 'ARM', 'name' => 'Armenia', 'nameFr' => 'Arménie', 'capital' => 'Yerevan', 'continent' => 'ASIA', 'callingCode' => '+374', 'currency' => 'AMD'],
            ['cca2' => 'AU', 'cca3' => 'AUS', 'name' => 'Australia', 'nameFr' => 'Australie', 'capital' => 'Canberra', 'continent' => 'OCEANIA', 'callingCode' => '+61', 'currency' => 'AUD'],
            ['cca2' => 'AT', 'cca3' => 'AUT', 'name' => 'Austria', 'nameFr' => 'Autriche', 'capital' => 'Vienna', 'continent' => 'EUROPE', 'callingCode' => '+43', 'currency' => 'EUR'],
            ['cca2' => 'AZ', 'cca3' => 'AZE', 'name' => 'Azerbaijan', 'nameFr' => 'Azerbaïdjan', 'capital' => 'Baku', 'continent' => 'ASIA', 'callingCode' => '+994', 'currency' => 'AZN'],
            ['cca2' => 'BS', 'cca3' => 'BHS', 'name' => 'Bahamas', 'nameFr' => 'Bahamas', 'capital' => 'Nassau', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1242', 'currency' => 'BSD'],
            ['cca2' => 'BH', 'cca3' => 'BHR', 'name' => 'Bahrain', 'nameFr' => 'Bahreïn', 'capital' => 'Manama', 'continent' => 'ASIA', 'callingCode' => '+973', 'currency' => 'BHD'],
            ['cca2' => 'BD', 'cca3' => 'BGD', 'name' => 'Bangladesh', 'nameFr' => 'Bangladesh', 'capital' => 'Dhaka', 'continent' => 'ASIA', 'callingCode' => '+880', 'currency' => 'BDT'],
            ['cca2' => 'BB', 'cca3' => 'BRB', 'name' => 'Barbados', 'nameFr' => 'Barbade', 'capital' => 'Bridgetown', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1246', 'currency' => 'BBD'],
            ['cca2' => 'BY', 'cca3' => 'BLR', 'name' => 'Belarus', 'nameFr' => 'Biélorussie', 'capital' => 'Minsk', 'continent' => 'EUROPE', 'callingCode' => '+375', 'currency' => 'BYN'],
            ['cca2' => 'BE', 'cca3' => 'BEL', 'name' => 'Belgium', 'nameFr' => 'Belgique', 'capital' => 'Brussels', 'continent' => 'EUROPE', 'callingCode' => '+32', 'currency' => 'EUR'],
            ['cca2' => 'BZ', 'cca3' => 'BLZ', 'name' => 'Belize', 'nameFr' => 'Belize', 'capital' => 'Belmopan', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+501', 'currency' => 'BZD'],
            ['cca2' => 'BJ', 'cca3' => 'BEN', 'name' => 'Benin', 'nameFr' => 'Bénin', 'capital' => 'Porto-Novo', 'continent' => 'AFRICA', 'callingCode' => '+229', 'currency' => 'XOF'],
            ['cca2' => 'BT', 'cca3' => 'BTN', 'name' => 'Bhutan', 'nameFr' => 'Bhoutan', 'capital' => 'Thimphu', 'continent' => 'ASIA', 'callingCode' => '+975', 'currency' => 'BTN'],
            ['cca2' => 'BO', 'cca3' => 'BOL', 'name' => 'Bolivia', 'nameFr' => 'Bolivie', 'capital' => 'Sucre', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+591', 'currency' => 'BOB'],
            ['cca2' => 'BA', 'cca3' => 'BIH', 'name' => 'Bosnia and Herzegovina', 'nameFr' => 'Bosnie-Herzégovine', 'capital' => 'Sarajevo', 'continent' => 'EUROPE', 'callingCode' => '+387', 'currency' => 'BAM'],
            ['cca2' => 'BW', 'cca3' => 'BWA', 'name' => 'Botswana', 'nameFr' => 'Botswana', 'capital' => 'Gaborone', 'continent' => 'AFRICA', 'callingCode' => '+267', 'currency' => 'BWP'],
            ['cca2' => 'BR', 'cca3' => 'BRA', 'name' => 'Brazil', 'nameFr' => 'Brésil', 'capital' => 'Brasília', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+55', 'currency' => 'BRL'],
            ['cca2' => 'BN', 'cca3' => 'BRN', 'name' => 'Brunei', 'nameFr' => 'Brunei', 'capital' => 'Bandar Seri Begawan', 'continent' => 'ASIA', 'callingCode' => '+673', 'currency' => 'BND'],
            ['cca2' => 'BG', 'cca3' => 'BGR', 'name' => 'Bulgaria', 'nameFr' => 'Bulgarie', 'capital' => 'Sofia', 'continent' => 'EUROPE', 'callingCode' => '+359', 'currency' => 'BGN'],
            ['cca2' => 'BF', 'cca3' => 'BFA', 'name' => 'Burkina Faso', 'nameFr' => 'Burkina Faso', 'capital' => 'Ouagadougou', 'continent' => 'AFRICA', 'callingCode' => '+226', 'currency' => 'XOF'],
            ['cca2' => 'BI', 'cca3' => 'BDI', 'name' => 'Burundi', 'nameFr' => 'Burundi', 'capital' => 'Gitega', 'continent' => 'AFRICA', 'callingCode' => '+257', 'currency' => 'BIF'],
            ['cca2' => 'KH', 'cca3' => 'KHM', 'name' => 'Cambodia', 'nameFr' => 'Cambodge', 'capital' => 'Phnom Penh', 'continent' => 'ASIA', 'callingCode' => '+855', 'currency' => 'KHR'],
            ['cca2' => 'CM', 'cca3' => 'CMR', 'name' => 'Cameroon', 'nameFr' => 'Cameroun', 'capital' => 'Yaoundé', 'continent' => 'AFRICA', 'callingCode' => '+237', 'currency' => 'XAF'],
            ['cca2' => 'CA', 'cca3' => 'CAN', 'name' => 'Canada', 'nameFr' => 'Canada', 'capital' => 'Ottawa', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1', 'currency' => 'CAD'],
            ['cca2' => 'CV', 'cca3' => 'CPV', 'name' => 'Cape Verde', 'nameFr' => 'Îles du Cap-Vert', 'capital' => 'Praia', 'continent' => 'AFRICA', 'callingCode' => '+238', 'currency' => 'CVE'],
            ['cca2' => 'CF', 'cca3' => 'CAF', 'name' => 'Central African Republic', 'nameFr' => 'République centrafricaine', 'capital' => 'Bangui', 'continent' => 'AFRICA', 'callingCode' => '+236', 'currency' => 'XAF'],
            ['cca2' => 'TD', 'cca3' => 'TCD', 'name' => 'Chad', 'nameFr' => 'Tchad', 'capital' => 'N\'Djamena', 'continent' => 'AFRICA', 'callingCode' => '+235', 'currency' => 'XAF'],
            ['cca2' => 'CL', 'cca3' => 'CHL', 'name' => 'Chile', 'nameFr' => 'Chili', 'capital' => 'Santiago', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+56', 'currency' => 'CLP'],
            ['cca2' => 'CN', 'cca3' => 'CHN', 'name' => 'China', 'nameFr' => 'Chine', 'capital' => 'Beijing', 'continent' => 'ASIA', 'callingCode' => '+86', 'currency' => 'CNY'],
            ['cca2' => 'CO', 'cca3' => 'COL', 'name' => 'Colombia', 'nameFr' => 'Colombie', 'capital' => 'Bogotá', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+57', 'currency' => 'COP'],
            ['cca2' => 'KM', 'cca3' => 'COM', 'name' => 'Comoros', 'nameFr' => 'Comores', 'capital' => 'Moroni', 'continent' => 'AFRICA', 'callingCode' => '+269', 'currency' => 'KMF'],
            ['cca2' => 'CG', 'cca3' => 'COG', 'name' => 'Congo', 'nameFr' => 'Congo', 'capital' => 'Brazzaville', 'continent' => 'AFRICA', 'callingCode' => '+242', 'currency' => 'XAF'],
            ['cca2' => 'CR', 'cca3' => 'CRI', 'name' => 'Costa Rica', 'nameFr' => 'Costa Rica', 'capital' => 'San José', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+506', 'currency' => 'CRC'],
            ['cca2' => 'HR', 'cca3' => 'HRV', 'name' => 'Croatia', 'nameFr' => 'Croatie', 'capital' => 'Zagreb', 'continent' => 'EUROPE', 'callingCode' => '+385', 'currency' => 'EUR'],
            ['cca2' => 'CU', 'cca3' => 'CUB', 'name' => 'Cuba', 'nameFr' => 'Cuba', 'capital' => 'Havana', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+53', 'currency' => 'CUC'],
            ['cca2' => 'CY', 'cca3' => 'CYP', 'name' => 'Cyprus', 'nameFr' => 'Chypre', 'capital' => 'Nicosia', 'continent' => 'EUROPE', 'callingCode' => '+357', 'currency' => 'EUR'],
            ['cca2' => 'CZ', 'cca3' => 'CZE', 'name' => 'Czechia', 'nameFr' => 'Tchéquie', 'capital' => 'Prague', 'continent' => 'EUROPE', 'callingCode' => '+420', 'currency' => 'CZK'],
            ['cca2' => 'CD', 'cca3' => 'COD', 'name' => 'DR Congo', 'nameFr' => 'Congo (Rép. dém.)', 'capital' => 'Kinshasa', 'continent' => 'AFRICA', 'callingCode' => '+243', 'currency' => 'CDF'],
            ['cca2' => 'DK', 'cca3' => 'DNK', 'name' => 'Denmark', 'nameFr' => 'Danemark', 'capital' => 'Copenhagen', 'continent' => 'EUROPE', 'callingCode' => '+45', 'currency' => 'DKK'],
            ['cca2' => 'DJ', 'cca3' => 'DJI', 'name' => 'Djibouti', 'nameFr' => 'Djibouti', 'capital' => 'Djibouti', 'continent' => 'AFRICA', 'callingCode' => '+253', 'currency' => 'DJF'],
            ['cca2' => 'DM', 'cca3' => 'DMA', 'name' => 'Dominica', 'nameFr' => 'Dominique', 'capital' => 'Roseau', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1767', 'currency' => 'XCD'],
            ['cca2' => 'DO', 'cca3' => 'DOM', 'name' => 'Dominican Republic', 'nameFr' => 'République dominicaine', 'capital' => 'Santo Domingo', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1', 'currency' => 'DOP'],
            ['cca2' => 'EC', 'cca3' => 'ECU', 'name' => 'Ecuador', 'nameFr' => 'Équateur', 'capital' => 'Quito', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+593', 'currency' => 'USD'],
            ['cca2' => 'EG', 'cca3' => 'EGY', 'name' => 'Egypt', 'nameFr' => 'Égypte', 'capital' => 'Cairo', 'continent' => 'AFRICA', 'callingCode' => '+20', 'currency' => 'EGP'],
            ['cca2' => 'SV', 'cca3' => 'SLV', 'name' => 'El Salvador', 'nameFr' => 'Salvador', 'capital' => 'San Salvador', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+503', 'currency' => 'USD'],
            ['cca2' => 'GQ', 'cca3' => 'GNQ', 'name' => 'Equatorial Guinea', 'nameFr' => 'Guinée équatoriale', 'capital' => 'Malabo', 'continent' => 'AFRICA', 'callingCode' => '+240', 'currency' => 'XAF'],
            ['cca2' => 'ER', 'cca3' => 'ERI', 'name' => 'Eritrea', 'nameFr' => 'Érythrée', 'capital' => 'Asmara', 'continent' => 'AFRICA', 'callingCode' => '+291', 'currency' => 'ERN'],
            ['cca2' => 'EE', 'cca3' => 'EST', 'name' => 'Estonia', 'nameFr' => 'Estonie', 'capital' => 'Tallinn', 'continent' => 'EUROPE', 'callingCode' => '+372', 'currency' => 'EUR'],
            ['cca2' => 'SZ', 'cca3' => 'SWZ', 'name' => 'Eswatini', 'nameFr' => 'Eswatini', 'capital' => 'Lobamba', 'continent' => 'AFRICA', 'callingCode' => '+268', 'currency' => 'SZL'],
            ['cca2' => 'ET', 'cca3' => 'ETH', 'name' => 'Ethiopia', 'nameFr' => 'Éthiopie', 'capital' => 'Addis Ababa', 'continent' => 'AFRICA', 'callingCode' => '+251', 'currency' => 'ETB'],
            ['cca2' => 'FJ', 'cca3' => 'FJI', 'name' => 'Fiji', 'nameFr' => 'Fidji', 'capital' => 'Suva', 'continent' => 'OCEANIA', 'callingCode' => '+679', 'currency' => 'FJD'],
            ['cca2' => 'FI', 'cca3' => 'FIN', 'name' => 'Finland', 'nameFr' => 'Finlande', 'capital' => 'Helsinki', 'continent' => 'EUROPE', 'callingCode' => '+358', 'currency' => 'EUR'],
            ['cca2' => 'FR', 'cca3' => 'FRA', 'name' => 'France', 'nameFr' => 'France', 'capital' => 'Paris', 'continent' => 'EUROPE', 'callingCode' => '+33', 'currency' => 'EUR'],
            ['cca2' => 'GA', 'cca3' => 'GAB', 'name' => 'Gabon', 'nameFr' => 'Gabon', 'capital' => 'Libreville', 'continent' => 'AFRICA', 'callingCode' => '+241', 'currency' => 'XAF'],
            ['cca2' => 'GM', 'cca3' => 'GMB', 'name' => 'Gambia', 'nameFr' => 'Gambie', 'capital' => 'Banjul', 'continent' => 'AFRICA', 'callingCode' => '+220', 'currency' => 'GMD'],
            ['cca2' => 'GE', 'cca3' => 'GEO', 'name' => 'Georgia', 'nameFr' => 'Géorgie', 'capital' => 'Tbilisi', 'continent' => 'ASIA', 'callingCode' => '+995', 'currency' => 'GEL'],
            ['cca2' => 'DE', 'cca3' => 'DEU', 'name' => 'Germany', 'nameFr' => 'Allemagne', 'capital' => 'Berlin', 'continent' => 'EUROPE', 'callingCode' => '+49', 'currency' => 'EUR'],
            ['cca2' => 'GH', 'cca3' => 'GHA', 'name' => 'Ghana', 'nameFr' => 'Ghana', 'capital' => 'Accra', 'continent' => 'AFRICA', 'callingCode' => '+233', 'currency' => 'GHS'],
            ['cca2' => 'GR', 'cca3' => 'GRC', 'name' => 'Greece', 'nameFr' => 'Grèce', 'capital' => 'Athens', 'continent' => 'EUROPE', 'callingCode' => '+30', 'currency' => 'EUR'],
            ['cca2' => 'GD', 'cca3' => 'GRD', 'name' => 'Grenada', 'nameFr' => 'Grenade', 'capital' => 'St. George\'s', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1473', 'currency' => 'XCD'],
            ['cca2' => 'GT', 'cca3' => 'GTM', 'name' => 'Guatemala', 'nameFr' => 'Guatemala', 'capital' => 'Guatemala City', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+502', 'currency' => 'GTQ'],
            ['cca2' => 'GN', 'cca3' => 'GIN', 'name' => 'Guinea', 'nameFr' => 'Guinée', 'capital' => 'Conakry', 'continent' => 'AFRICA', 'callingCode' => '+224', 'currency' => 'GNF'],
            ['cca2' => 'GW', 'cca3' => 'GNB', 'name' => 'Guinea-Bissau', 'nameFr' => 'Guinée-Bissau', 'capital' => 'Bissau', 'continent' => 'AFRICA', 'callingCode' => '+245', 'currency' => 'XOF'],
            ['cca2' => 'GY', 'cca3' => 'GUY', 'name' => 'Guyana', 'nameFr' => 'Guyana', 'capital' => 'Georgetown', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+592', 'currency' => 'GYD'],
            ['cca2' => 'HT', 'cca3' => 'HTI', 'name' => 'Haiti', 'nameFr' => 'Haïti', 'capital' => 'Port-au-Prince', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+509', 'currency' => 'HTG'],
            ['cca2' => 'HN', 'cca3' => 'HND', 'name' => 'Honduras', 'nameFr' => 'Honduras', 'capital' => 'Tegucigalpa', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+504', 'currency' => 'HNL'],
            ['cca2' => 'HU', 'cca3' => 'HUN', 'name' => 'Hungary', 'nameFr' => 'Hongrie', 'capital' => 'Budapest', 'continent' => 'EUROPE', 'callingCode' => '+36', 'currency' => 'HUF'],
            ['cca2' => 'IS', 'cca3' => 'ISL', 'name' => 'Iceland', 'nameFr' => 'Islande', 'capital' => 'Reykjavik', 'continent' => 'EUROPE', 'callingCode' => '+354', 'currency' => 'ISK'],
            ['cca2' => 'IN', 'cca3' => 'IND', 'name' => 'India', 'nameFr' => 'Inde', 'capital' => 'New Delhi', 'continent' => 'ASIA', 'callingCode' => '+91', 'currency' => 'INR'],
            ['cca2' => 'ID', 'cca3' => 'IDN', 'name' => 'Indonesia', 'nameFr' => 'Indonésie', 'capital' => 'Jakarta', 'continent' => 'ASIA', 'callingCode' => '+62', 'currency' => 'IDR'],
            ['cca2' => 'IR', 'cca3' => 'IRN', 'name' => 'Iran', 'nameFr' => 'Iran', 'capital' => 'Tehran', 'continent' => 'ASIA', 'callingCode' => '+98', 'currency' => 'IRR'],
            ['cca2' => 'IQ', 'cca3' => 'IRQ', 'name' => 'Iraq', 'nameFr' => 'Irak', 'capital' => 'Baghdad', 'continent' => 'ASIA', 'callingCode' => '+964', 'currency' => 'IQD'],
            ['cca2' => 'IE', 'cca3' => 'IRL', 'name' => 'Ireland', 'nameFr' => 'Irlande', 'capital' => 'Dublin', 'continent' => 'EUROPE', 'callingCode' => '+353', 'currency' => 'EUR'],
            ['cca2' => 'IL', 'cca3' => 'ISR', 'name' => 'Israel', 'nameFr' => 'Israël', 'capital' => 'Jerusalem', 'continent' => 'ASIA', 'callingCode' => '+972', 'currency' => 'ILS'],
            ['cca2' => 'IT', 'cca3' => 'ITA', 'name' => 'Italy', 'nameFr' => 'Italie', 'capital' => 'Rome', 'continent' => 'EUROPE', 'callingCode' => '+39', 'currency' => 'EUR'],
            ['cca2' => 'CI', 'cca3' => 'CIV', 'name' => 'Ivory Coast', 'nameFr' => 'Côte d\'Ivoire', 'capital' => 'Yamoussoukro', 'continent' => 'AFRICA', 'callingCode' => '+225', 'currency' => 'XOF'],
            ['cca2' => 'JM', 'cca3' => 'JAM', 'name' => 'Jamaica', 'nameFr' => 'Jamaïque', 'capital' => 'Kingston', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1876', 'currency' => 'JMD'],
            ['cca2' => 'JP', 'cca3' => 'JPN', 'name' => 'Japan', 'nameFr' => 'Japon', 'capital' => 'Tokyo', 'continent' => 'ASIA', 'callingCode' => '+81', 'currency' => 'JPY'],
            ['cca2' => 'JO', 'cca3' => 'JOR', 'name' => 'Jordan', 'nameFr' => 'Jordanie', 'capital' => 'Amman', 'continent' => 'ASIA', 'callingCode' => '+962', 'currency' => 'JOD'],
            ['cca2' => 'KZ', 'cca3' => 'KAZ', 'name' => 'Kazakhstan', 'nameFr' => 'Kazakhstan', 'capital' => 'Astana', 'continent' => 'ASIA', 'callingCode' => '+7', 'currency' => 'KZT'],
            ['cca2' => 'KE', 'cca3' => 'KEN', 'name' => 'Kenya', 'nameFr' => 'Kenya', 'capital' => 'Nairobi', 'continent' => 'AFRICA', 'callingCode' => '+254', 'currency' => 'KES'],
            ['cca2' => 'KI', 'cca3' => 'KIR', 'name' => 'Kiribati', 'nameFr' => 'Kiribati', 'capital' => 'South Tarawa', 'continent' => 'OCEANIA', 'callingCode' => '+686', 'currency' => 'AUD'],
            ['cca2' => 'KW', 'cca3' => 'KWT', 'name' => 'Kuwait', 'nameFr' => 'Koweït', 'capital' => 'Kuwait City', 'continent' => 'ASIA', 'callingCode' => '+965', 'currency' => 'KWD'],
            ['cca2' => 'KG', 'cca3' => 'KGZ', 'name' => 'Kyrgyzstan', 'nameFr' => 'Kirghizistan', 'capital' => 'Bishkek', 'continent' => 'ASIA', 'callingCode' => '+996', 'currency' => 'KGS'],
            ['cca2' => 'LA', 'cca3' => 'LAO', 'name' => 'Laos', 'nameFr' => 'Laos', 'capital' => 'Vientiane', 'continent' => 'ASIA', 'callingCode' => '+856', 'currency' => 'LAK'],
            ['cca2' => 'LV', 'cca3' => 'LVA', 'name' => 'Latvia', 'nameFr' => 'Lettonie', 'capital' => 'Riga', 'continent' => 'EUROPE', 'callingCode' => '+371', 'currency' => 'EUR'],
            ['cca2' => 'LB', 'cca3' => 'LBN', 'name' => 'Lebanon', 'nameFr' => 'Liban', 'capital' => 'Beirut', 'continent' => 'ASIA', 'callingCode' => '+961', 'currency' => 'LBP'],
            ['cca2' => 'LS', 'cca3' => 'LSO', 'name' => 'Lesotho', 'nameFr' => 'Lesotho', 'capital' => 'Maseru', 'continent' => 'AFRICA', 'callingCode' => '+266', 'currency' => 'LSL'],
            ['cca2' => 'LR', 'cca3' => 'LBR', 'name' => 'Liberia', 'nameFr' => 'Liberia', 'capital' => 'Monrovia', 'continent' => 'AFRICA', 'callingCode' => '+231', 'currency' => 'LRD'],
            ['cca2' => 'LY', 'cca3' => 'LBY', 'name' => 'Libya', 'nameFr' => 'Libye', 'capital' => 'Tripoli', 'continent' => 'AFRICA', 'callingCode' => '+218', 'currency' => 'LYD'],
            ['cca2' => 'LI', 'cca3' => 'LIE', 'name' => 'Liechtenstein', 'nameFr' => 'Liechtenstein', 'capital' => 'Vaduz', 'continent' => 'EUROPE', 'callingCode' => '+423', 'currency' => 'CHF'],
            ['cca2' => 'LT', 'cca3' => 'LTU', 'name' => 'Lithuania', 'nameFr' => 'Lituanie', 'capital' => 'Vilnius', 'continent' => 'EUROPE', 'callingCode' => '+370', 'currency' => 'EUR'],
            ['cca2' => 'LU', 'cca3' => 'LUX', 'name' => 'Luxembourg', 'nameFr' => 'Luxembourg', 'capital' => 'Luxembourg', 'continent' => 'EUROPE', 'callingCode' => '+352', 'currency' => 'EUR'],
            ['cca2' => 'MG', 'cca3' => 'MDG', 'name' => 'Madagascar', 'nameFr' => 'Madagascar', 'capital' => 'Antananarivo', 'continent' => 'AFRICA', 'callingCode' => '+261', 'currency' => 'MGA'],
            ['cca2' => 'MW', 'cca3' => 'MWI', 'name' => 'Malawi', 'nameFr' => 'Malawi', 'capital' => 'Lilongwe', 'continent' => 'AFRICA', 'callingCode' => '+265', 'currency' => 'MWK'],
            ['cca2' => 'MY', 'cca3' => 'MYS', 'name' => 'Malaysia', 'nameFr' => 'Malaisie', 'capital' => 'Kuala Lumpur', 'continent' => 'ASIA', 'callingCode' => '+60', 'currency' => 'MYR'],
            ['cca2' => 'MV', 'cca3' => 'MDV', 'name' => 'Maldives', 'nameFr' => 'Maldives', 'capital' => 'Malé', 'continent' => 'ASIA', 'callingCode' => '+960', 'currency' => 'MVR'],
            ['cca2' => 'ML', 'cca3' => 'MLI', 'name' => 'Mali', 'nameFr' => 'Mali', 'capital' => 'Bamako', 'continent' => 'AFRICA', 'callingCode' => '+223', 'currency' => 'XOF'],
            ['cca2' => 'MT', 'cca3' => 'MLT', 'name' => 'Malta', 'nameFr' => 'Malte', 'capital' => 'Valletta', 'continent' => 'EUROPE', 'callingCode' => '+356', 'currency' => 'EUR'],
            ['cca2' => 'MH', 'cca3' => 'MHL', 'name' => 'Marshall Islands', 'nameFr' => 'Îles Marshall', 'capital' => 'Majuro', 'continent' => 'OCEANIA', 'callingCode' => '+692', 'currency' => 'USD'],
            ['cca2' => 'MR', 'cca3' => 'MRT', 'name' => 'Mauritania', 'nameFr' => 'Mauritanie', 'capital' => 'Nouakchott', 'continent' => 'AFRICA', 'callingCode' => '+222', 'currency' => 'MRU'],
            ['cca2' => 'MU', 'cca3' => 'MUS', 'name' => 'Mauritius', 'nameFr' => 'Île Maurice', 'capital' => 'Port Louis', 'continent' => 'AFRICA', 'callingCode' => '+230', 'currency' => 'MUR'],
            ['cca2' => 'MX', 'cca3' => 'MEX', 'name' => 'Mexico', 'nameFr' => 'Mexique', 'capital' => 'Mexico City', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+52', 'currency' => 'MXN'],
            ['cca2' => 'FM', 'cca3' => 'FSM', 'name' => 'Micronesia', 'nameFr' => 'Micronésie', 'capital' => 'Palikir', 'continent' => 'OCEANIA', 'callingCode' => '+691', 'currency' => ''],
            ['cca2' => 'MD', 'cca3' => 'MDA', 'name' => 'Moldova', 'nameFr' => 'Moldavie', 'capital' => 'Chișinău', 'continent' => 'EUROPE', 'callingCode' => '+373', 'currency' => 'MDL'],
            ['cca2' => 'MC', 'cca3' => 'MCO', 'name' => 'Monaco', 'nameFr' => 'Monaco', 'capital' => 'Monaco', 'continent' => 'EUROPE', 'callingCode' => '+377', 'currency' => 'EUR'],
            ['cca2' => 'MN', 'cca3' => 'MNG', 'name' => 'Mongolia', 'nameFr' => 'Mongolie', 'capital' => 'Ulan Bator', 'continent' => 'ASIA', 'callingCode' => '+976', 'currency' => 'MNT'],
            ['cca2' => 'ME', 'cca3' => 'MNE', 'name' => 'Montenegro', 'nameFr' => 'Monténégro', 'capital' => 'Podgorica', 'continent' => 'EUROPE', 'callingCode' => '+382', 'currency' => 'EUR'],
            ['cca2' => 'MA', 'cca3' => 'MAR', 'name' => 'Morocco', 'nameFr' => 'Maroc', 'capital' => 'Rabat', 'continent' => 'AFRICA', 'callingCode' => '+212', 'currency' => 'MAD'],
            ['cca2' => 'MZ', 'cca3' => 'MOZ', 'name' => 'Mozambique', 'nameFr' => 'Mozambique', 'capital' => 'Maputo', 'continent' => 'AFRICA', 'callingCode' => '+258', 'currency' => 'MZN'],
            ['cca2' => 'MM', 'cca3' => 'MMR', 'name' => 'Myanmar', 'nameFr' => 'Birmanie', 'capital' => 'Naypyidaw', 'continent' => 'ASIA', 'callingCode' => '+95', 'currency' => 'MMK'],
            ['cca2' => 'NA', 'cca3' => 'NAM', 'name' => 'Namibia', 'nameFr' => 'Namibie', 'capital' => 'Windhoek', 'continent' => 'AFRICA', 'callingCode' => '+264', 'currency' => 'NAD'],
            ['cca2' => 'NR', 'cca3' => 'NRU', 'name' => 'Nauru', 'nameFr' => 'Nauru', 'capital' => 'Yaren', 'continent' => 'OCEANIA', 'callingCode' => '+674', 'currency' => 'AUD'],
            ['cca2' => 'NP', 'cca3' => 'NPL', 'name' => 'Nepal', 'nameFr' => 'Népal', 'capital' => 'Kathmandu', 'continent' => 'ASIA', 'callingCode' => '+977', 'currency' => 'NPR'],
            ['cca2' => 'NL', 'cca3' => 'NLD', 'name' => 'Netherlands', 'nameFr' => 'Pays-Bas', 'capital' => 'Amsterdam', 'continent' => 'EUROPE', 'callingCode' => '+31', 'currency' => 'EUR'],
            ['cca2' => 'NZ', 'cca3' => 'NZL', 'name' => 'New Zealand', 'nameFr' => 'Nouvelle-Zélande', 'capital' => 'Wellington', 'continent' => 'OCEANIA', 'callingCode' => '+64', 'currency' => 'NZD'],
            ['cca2' => 'NI', 'cca3' => 'NIC', 'name' => 'Nicaragua', 'nameFr' => 'Nicaragua', 'capital' => 'Managua', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+505', 'currency' => 'NIO'],
            ['cca2' => 'NE', 'cca3' => 'NER', 'name' => 'Niger', 'nameFr' => 'Niger', 'capital' => 'Niamey', 'continent' => 'AFRICA', 'callingCode' => '+227', 'currency' => 'XOF'],
            ['cca2' => 'NG', 'cca3' => 'NGA', 'name' => 'Nigeria', 'nameFr' => 'Nigéria', 'capital' => 'Abuja', 'continent' => 'AFRICA', 'callingCode' => '+234', 'currency' => 'NGN'],
            ['cca2' => 'KP', 'cca3' => 'PRK', 'name' => 'North Korea', 'nameFr' => 'Corée du Nord', 'capital' => 'Pyongyang', 'continent' => 'ASIA', 'callingCode' => '+850', 'currency' => 'KPW'],
            ['cca2' => 'MK', 'cca3' => 'MKD', 'name' => 'North Macedonia', 'nameFr' => 'Macédoine du Nord', 'capital' => 'Skopje', 'continent' => 'EUROPE', 'callingCode' => '+389', 'currency' => 'MKD'],
            ['cca2' => 'NO', 'cca3' => 'NOR', 'name' => 'Norway', 'nameFr' => 'Norvège', 'capital' => 'Oslo', 'continent' => 'EUROPE', 'callingCode' => '+47', 'currency' => 'NOK'],
            ['cca2' => 'OM', 'cca3' => 'OMN', 'name' => 'Oman', 'nameFr' => 'Oman', 'capital' => 'Muscat', 'continent' => 'ASIA', 'callingCode' => '+968', 'currency' => 'OMR'],
            ['cca2' => 'PK', 'cca3' => 'PAK', 'name' => 'Pakistan', 'nameFr' => 'Pakistan', 'capital' => 'Islamabad', 'continent' => 'ASIA', 'callingCode' => '+92', 'currency' => 'PKR'],
            ['cca2' => 'PW', 'cca3' => 'PLW', 'name' => 'Palau', 'nameFr' => 'Palaos (Palau)', 'capital' => 'Ngerulmud', 'continent' => 'OCEANIA', 'callingCode' => '+680', 'currency' => 'USD'],
            ['cca2' => 'PA', 'cca3' => 'PAN', 'name' => 'Panama', 'nameFr' => 'Panama', 'capital' => 'Panama City', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+507', 'currency' => 'PAB'],
            ['cca2' => 'PG', 'cca3' => 'PNG', 'name' => 'Papua New Guinea', 'nameFr' => 'Papouasie-Nouvelle-Guinée', 'capital' => 'Port Moresby', 'continent' => 'OCEANIA', 'callingCode' => '+675', 'currency' => 'PGK'],
            ['cca2' => 'PY', 'cca3' => 'PRY', 'name' => 'Paraguay', 'nameFr' => 'Paraguay', 'capital' => 'Asunción', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+595', 'currency' => 'PYG'],
            ['cca2' => 'PE', 'cca3' => 'PER', 'name' => 'Peru', 'nameFr' => 'Pérou', 'capital' => 'Lima', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+51', 'currency' => 'PEN'],
            ['cca2' => 'PH', 'cca3' => 'PHL', 'name' => 'Philippines', 'nameFr' => 'Philippines', 'capital' => 'Manila', 'continent' => 'ASIA', 'callingCode' => '+63', 'currency' => 'PHP'],
            ['cca2' => 'PL', 'cca3' => 'POL', 'name' => 'Poland', 'nameFr' => 'Pologne', 'capital' => 'Warsaw', 'continent' => 'EUROPE', 'callingCode' => '+48', 'currency' => 'PLN'],
            ['cca2' => 'PT', 'cca3' => 'PRT', 'name' => 'Portugal', 'nameFr' => 'Portugal', 'capital' => 'Lisbon', 'continent' => 'EUROPE', 'callingCode' => '+351', 'currency' => 'EUR'],
            ['cca2' => 'QA', 'cca3' => 'QAT', 'name' => 'Qatar', 'nameFr' => 'Qatar', 'capital' => 'Doha', 'continent' => 'ASIA', 'callingCode' => '+974', 'currency' => 'QAR'],
            ['cca2' => 'RO', 'cca3' => 'ROU', 'name' => 'Romania', 'nameFr' => 'Roumanie', 'capital' => 'Bucharest', 'continent' => 'EUROPE', 'callingCode' => '+40', 'currency' => 'RON'],
            ['cca2' => 'RU', 'cca3' => 'RUS', 'name' => 'Russia', 'nameFr' => 'Russie', 'capital' => 'Moscow', 'continent' => 'EUROPE', 'callingCode' => '+7', 'currency' => 'RUB'],
            ['cca2' => 'RW', 'cca3' => 'RWA', 'name' => 'Rwanda', 'nameFr' => 'Rwanda', 'capital' => 'Kigali', 'continent' => 'AFRICA', 'callingCode' => '+250', 'currency' => 'RWF'],
            ['cca2' => 'KN', 'cca3' => 'KNA', 'name' => 'Saint Kitts and Nevis', 'nameFr' => 'Saint-Christophe-et-Niévès', 'capital' => 'Basseterre', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1869', 'currency' => 'XCD'],
            ['cca2' => 'LC', 'cca3' => 'LCA', 'name' => 'Saint Lucia', 'nameFr' => 'Sainte-Lucie', 'capital' => 'Castries', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1758', 'currency' => 'XCD'],
            ['cca2' => 'VC', 'cca3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines', 'nameFr' => 'Saint-Vincent-et-les-Grenadines', 'capital' => 'Kingstown', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1784', 'currency' => 'XCD'],
            ['cca2' => 'WS', 'cca3' => 'WSM', 'name' => 'Samoa', 'nameFr' => 'Samoa', 'capital' => 'Apia', 'continent' => 'OCEANIA', 'callingCode' => '+685', 'currency' => 'WST'],
            ['cca2' => 'SM', 'cca3' => 'SMR', 'name' => 'San Marino', 'nameFr' => 'Saint-Marin', 'capital' => 'City of San Marino', 'continent' => 'EUROPE', 'callingCode' => '+378', 'currency' => 'EUR'],
            ['cca2' => 'SA', 'cca3' => 'SAU', 'name' => 'Saudi Arabia', 'nameFr' => 'Arabie Saoudite', 'capital' => 'Riyadh', 'continent' => 'ASIA', 'callingCode' => '+966', 'currency' => 'SAR'],
            ['cca2' => 'SN', 'cca3' => 'SEN', 'name' => 'Senegal', 'nameFr' => 'Sénégal', 'capital' => 'Dakar', 'continent' => 'AFRICA', 'callingCode' => '+221', 'currency' => 'XOF'],
            ['cca2' => 'RS', 'cca3' => 'SRB', 'name' => 'Serbia', 'nameFr' => 'Serbie', 'capital' => 'Belgrade', 'continent' => 'EUROPE', 'callingCode' => '+381', 'currency' => 'RSD'],
            ['cca2' => 'SC', 'cca3' => 'SYC', 'name' => 'Seychelles', 'nameFr' => 'Seychelles', 'capital' => 'Victoria', 'continent' => 'AFRICA', 'callingCode' => '+248', 'currency' => 'SCR'],
            ['cca2' => 'SL', 'cca3' => 'SLE', 'name' => 'Sierra Leone', 'nameFr' => 'Sierra Leone', 'capital' => 'Freetown', 'continent' => 'AFRICA', 'callingCode' => '+232', 'currency' => 'SLL'],
            ['cca2' => 'SG', 'cca3' => 'SGP', 'name' => 'Singapore', 'nameFr' => 'Singapour', 'capital' => 'Singapore', 'continent' => 'ASIA', 'callingCode' => '+65', 'currency' => 'SGD'],
            ['cca2' => 'SK', 'cca3' => 'SVK', 'name' => 'Slovakia', 'nameFr' => 'Slovaquie', 'capital' => 'Bratislava', 'continent' => 'EUROPE', 'callingCode' => '+421', 'currency' => 'EUR'],
            ['cca2' => 'SI', 'cca3' => 'SVN', 'name' => 'Slovenia', 'nameFr' => 'Slovénie', 'capital' => 'Ljubljana', 'continent' => 'EUROPE', 'callingCode' => '+386', 'currency' => 'EUR'],
            ['cca2' => 'SB', 'cca3' => 'SLB', 'name' => 'Solomon Islands', 'nameFr' => 'Îles Salomon', 'capital' => 'Honiara', 'continent' => 'OCEANIA', 'callingCode' => '+677', 'currency' => 'SBD'],
            ['cca2' => 'SO', 'cca3' => 'SOM', 'name' => 'Somalia', 'nameFr' => 'Somalie', 'capital' => 'Mogadishu', 'continent' => 'AFRICA', 'callingCode' => '+252', 'currency' => 'SOS'],
            ['cca2' => 'ZA', 'cca3' => 'ZAF', 'name' => 'South Africa', 'nameFr' => 'Afrique du Sud', 'capital' => 'Pretoria', 'continent' => 'AFRICA', 'callingCode' => '+27', 'currency' => 'ZAR'],
            ['cca2' => 'KR', 'cca3' => 'KOR', 'name' => 'South Korea', 'nameFr' => 'Corée du Sud', 'capital' => 'Seoul', 'continent' => 'ASIA', 'callingCode' => '+82', 'currency' => 'KRW'],
            ['cca2' => 'SS', 'cca3' => 'SSD', 'name' => 'South Sudan', 'nameFr' => 'Soudan du Sud', 'capital' => 'Juba', 'continent' => 'AFRICA', 'callingCode' => '+211', 'currency' => 'SSP'],
            ['cca2' => 'ES', 'cca3' => 'ESP', 'name' => 'Spain', 'nameFr' => 'Espagne', 'capital' => 'Madrid', 'continent' => 'EUROPE', 'callingCode' => '+34', 'currency' => 'EUR'],
            ['cca2' => 'LK', 'cca3' => 'LKA', 'name' => 'Sri Lanka', 'nameFr' => 'Sri Lanka', 'capital' => 'Colombo', 'continent' => 'ASIA', 'callingCode' => '+94', 'currency' => 'LKR'],
            ['cca2' => 'SD', 'cca3' => 'SDN', 'name' => 'Sudan', 'nameFr' => 'Soudan', 'capital' => 'Khartoum', 'continent' => 'AFRICA', 'callingCode' => '+249', 'currency' => 'SDG'],
            ['cca2' => 'SR', 'cca3' => 'SUR', 'name' => 'Suriname', 'nameFr' => 'Surinam', 'capital' => 'Paramaribo', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+597', 'currency' => 'SRD'],
            ['cca2' => 'SE', 'cca3' => 'SWE', 'name' => 'Sweden', 'nameFr' => 'Suède', 'capital' => 'Stockholm', 'continent' => 'EUROPE', 'callingCode' => '+46', 'currency' => 'SEK'],
            ['cca2' => 'CH', 'cca3' => 'CHE', 'name' => 'Switzerland', 'nameFr' => 'Suisse', 'capital' => 'Bern', 'continent' => 'EUROPE', 'callingCode' => '+41', 'currency' => 'CHF'],
            ['cca2' => 'SY', 'cca3' => 'SYR', 'name' => 'Syria', 'nameFr' => 'Syrie', 'capital' => 'Damascus', 'continent' => 'ASIA', 'callingCode' => '+963', 'currency' => 'SYP'],
            ['cca2' => 'ST', 'cca3' => 'STP', 'name' => 'São Tomé and Príncipe', 'nameFr' => 'São Tomé et Príncipe', 'capital' => 'São Tomé', 'continent' => 'AFRICA', 'callingCode' => '+239', 'currency' => 'STN'],
            ['cca2' => 'TJ', 'cca3' => 'TJK', 'name' => 'Tajikistan', 'nameFr' => 'Tadjikistan', 'capital' => 'Dushanbe', 'continent' => 'ASIA', 'callingCode' => '+992', 'currency' => 'TJS'],
            ['cca2' => 'TZ', 'cca3' => 'TZA', 'name' => 'Tanzania', 'nameFr' => 'Tanzanie', 'capital' => 'Dodoma', 'continent' => 'AFRICA', 'callingCode' => '+255', 'currency' => 'TZS'],
            ['cca2' => 'TH', 'cca3' => 'THA', 'name' => 'Thailand', 'nameFr' => 'Thaïlande', 'capital' => 'Bangkok', 'continent' => 'ASIA', 'callingCode' => '+66', 'currency' => 'THB'],
            ['cca2' => 'TL', 'cca3' => 'TLS', 'name' => 'Timor-Leste', 'nameFr' => 'Timor oriental', 'capital' => 'Dili', 'continent' => 'ASIA', 'callingCode' => '+670', 'currency' => 'USD'],
            ['cca2' => 'TG', 'cca3' => 'TGO', 'name' => 'Togo', 'nameFr' => 'Togo', 'capital' => 'Lomé', 'continent' => 'AFRICA', 'callingCode' => '+228', 'currency' => 'XOF'],
            ['cca2' => 'TO', 'cca3' => 'TON', 'name' => 'Tonga', 'nameFr' => 'Tonga', 'capital' => 'Nuku\'alofa', 'continent' => 'OCEANIA', 'callingCode' => '+676', 'currency' => 'TOP'],
            ['cca2' => 'TT', 'cca3' => 'TTO', 'name' => 'Trinidad and Tobago', 'nameFr' => 'Trinité-et-Tobago', 'capital' => 'Port of Spain', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1868', 'currency' => 'TTD'],
            ['cca2' => 'TN', 'cca3' => 'TUN', 'name' => 'Tunisia', 'nameFr' => 'Tunisie', 'capital' => 'Tunis', 'continent' => 'AFRICA', 'callingCode' => '+216', 'currency' => 'TND'],
            ['cca2' => 'TM', 'cca3' => 'TKM', 'name' => 'Turkmenistan', 'nameFr' => 'Turkménistan', 'capital' => 'Ashgabat', 'continent' => 'ASIA', 'callingCode' => '+993', 'currency' => 'TMT'],
            ['cca2' => 'TV', 'cca3' => 'TUV', 'name' => 'Tuvalu', 'nameFr' => 'Tuvalu', 'capital' => 'Funafuti', 'continent' => 'OCEANIA', 'callingCode' => '+688', 'currency' => 'AUD'],
            ['cca2' => 'TR', 'cca3' => 'TUR', 'name' => 'Türkiye', 'nameFr' => 'Turquie', 'capital' => 'Ankara', 'continent' => 'ASIA', 'callingCode' => '+90', 'currency' => 'TRY'],
            ['cca2' => 'UG', 'cca3' => 'UGA', 'name' => 'Uganda', 'nameFr' => 'Ouganda', 'capital' => 'Kampala', 'continent' => 'AFRICA', 'callingCode' => '+256', 'currency' => 'UGX'],
            ['cca2' => 'UA', 'cca3' => 'UKR', 'name' => 'Ukraine', 'nameFr' => 'Ukraine', 'capital' => 'Kyiv', 'continent' => 'EUROPE', 'callingCode' => '+380', 'currency' => 'UAH'],
            ['cca2' => 'AE', 'cca3' => 'ARE', 'name' => 'United Arab Emirates', 'nameFr' => 'Émirats arabes unis', 'capital' => 'Abu Dhabi', 'continent' => 'ASIA', 'callingCode' => '+971', 'currency' => 'AED'],
            ['cca2' => 'GB', 'cca3' => 'GBR', 'name' => 'United Kingdom', 'nameFr' => 'Royaume-Uni', 'capital' => 'London', 'continent' => 'EUROPE', 'callingCode' => '+44', 'currency' => 'GBP'],
            ['cca2' => 'US', 'cca3' => 'USA', 'name' => 'United States', 'nameFr' => 'États-Unis', 'capital' => 'Washington D.C.', 'continent' => 'NORTH_AMERICA', 'callingCode' => '+1', 'currency' => 'USD'],
            ['cca2' => 'UY', 'cca3' => 'URY', 'name' => 'Uruguay', 'nameFr' => 'Uruguay', 'capital' => 'Montevideo', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+598', 'currency' => 'UYU'],
            ['cca2' => 'UZ', 'cca3' => 'UZB', 'name' => 'Uzbekistan', 'nameFr' => 'Ouzbékistan', 'capital' => 'Tashkent', 'continent' => 'ASIA', 'callingCode' => '+998', 'currency' => 'UZS'],
            ['cca2' => 'VU', 'cca3' => 'VUT', 'name' => 'Vanuatu', 'nameFr' => 'Vanuatu', 'capital' => 'Port Vila', 'continent' => 'OCEANIA', 'callingCode' => '+678', 'currency' => 'VUV'],
            ['cca2' => 'VA', 'cca3' => 'VAT', 'name' => 'Vatican City', 'nameFr' => 'Cité du Vatican', 'capital' => 'Vatican City', 'continent' => 'EUROPE', 'callingCode' => '+3', 'currency' => 'EUR'],
            ['cca2' => 'VE', 'cca3' => 'VEN', 'name' => 'Venezuela', 'nameFr' => 'Venezuela', 'capital' => 'Caracas', 'continent' => 'SOUTH_AMERICA', 'callingCode' => '+58', 'currency' => 'VES'],
            ['cca2' => 'VN', 'cca3' => 'VNM', 'name' => 'Vietnam', 'nameFr' => 'Viêt Nam', 'capital' => 'Hanoi', 'continent' => 'ASIA', 'callingCode' => '+84', 'currency' => 'VND'],
            ['cca2' => 'YE', 'cca3' => 'YEM', 'name' => 'Yemen', 'nameFr' => 'Yémen', 'capital' => 'Sana\'a', 'continent' => 'ASIA', 'callingCode' => '+967', 'currency' => 'YER'],
            ['cca2' => 'ZM', 'cca3' => 'ZMB', 'name' => 'Zambia', 'nameFr' => 'Zambie', 'capital' => 'Lusaka', 'continent' => 'AFRICA', 'callingCode' => '+260', 'currency' => 'ZMW'],
            ['cca2' => 'ZW', 'cca3' => 'ZWE', 'name' => 'Zimbabwe', 'nameFr' => 'Zimbabwe', 'capital' => 'Harare', 'continent' => 'AFRICA', 'callingCode' => '+263', 'currency' => 'BWP'],
        ];
    }
}
